# Generated by Django 6.0.4 on 2026-07-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "org_building",
                "ordering": ["hotel", "code"],
                "unique_together": {("hotel", "code")},
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="identity.building",
                    ),
                ),
            ],
            options={
                "db_table": "org_floor",
                "ordering": ["building", "number"],
            },
        ),
        migrations.CreateModel(
            name="HotelResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=140)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("EQUIPMENT", "Equipamento"),
                            ("VEHICLE", "Viatura"),
                            ("IT", "Informática"),
                            ("FURNITURE", "Mobiliário"),
                            ("HVAC", "AVAC/Climatização"),
                            ("OTHER", "Outro"),
                        ],
                        default="EQUIPMENT",
                        max_length=12,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Operacional"),
                            ("MAINTENANCE", "Em manutenção"),
                            ("RETIRED", "Abatido"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "org_resource",
                "ordering": ["hotel", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProfitCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=120)),
                ("manager", models.CharField(blank=True, max_length=120, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profit_centers",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "org_profit_center",
                "ordering": ["hotel", "code"],
                "unique_together": {("hotel", "code")},
            },
        ),
    ]
