# Generated by Django 6.0.4 on 2026-07-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0003_userhotelaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="check_in_time",
            field=models.TimeField(default="14:00"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="check_out_time",
            field=models.TimeField(default="12:00"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="city",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="country",
            field=models.CharField(default="Angola", max_length=80),
        ),
        migrations.AddField(
            model_name="hotel",
            name="currency",
            field=models.CharField(default="AOA", max_length=10),
        ),
        migrations.AddField(
            model_name="hotel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_type",
            field=models.CharField(default="Hotel", max_length=40),
        ),
        migrations.AddField(
            model_name="hotel",
            name="opened_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="phone",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="province",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="stars",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="hotel",
            name="timezone",
            field=models.CharField(default="Africa/Luanda", max_length=50),
        ),
        migrations.AddField(
            model_name="hotel",
            name="website",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
