# Generated by Django 6.0.4 on 2026-07-12 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0004_hotel_address_hotel_check_in_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprisegroup",
            name="code",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="enterprisegroup",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="enterprisegroup",
            name="sort_order",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name="GroupCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=60)),
                ("symbol", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=6, default=1, max_digits=14),
                ),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currencies",
                        to="identity.enterprisegroup",
                    ),
                ),
            ],
            options={
                "db_table": "idn_group_currency",
                "ordering": ["sort_order"],
                "unique_together": {("group", "code")},
            },
        ),
        migrations.CreateModel(
            name="GroupLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("culture_code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=80)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("legacy_code", models.CharField(blank=True, max_length=10, null=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="identity.enterprisegroup",
                    ),
                ),
            ],
            options={
                "db_table": "idn_group_language",
                "ordering": ["sort_order"],
                "unique_together": {("group", "culture_code")},
            },
        ),
    ]
