# Generated by Django 6.0.4 on 2026-07-12 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0005_enterprisegroup_code_enterprisegroup_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="address2",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="bg_color",
            field=models.CharField(default="#808080", max_length=20),
        ),
        migrations.AddField(
            model_name="hotel",
            name="country_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="external_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="fax",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="is_master",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="logo_url",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="name2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="nif",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="platform_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="pos_location_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="postal_code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="sec_address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="sec_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="sec_phone",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="specific_timezone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="text_color",
            field=models.CharField(default="white", max_length=20),
        ),
        migrations.CreateModel(
            name="HotelCustomText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=120)),
                ("text", models.CharField(blank=True, max_length=400, null=True)),
                ("source", models.CharField(blank=True, max_length=80, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("bold", models.BooleanField(default=False)),
                ("italic", models.BooleanField(default=False)),
                ("font_size", models.PositiveIntegerField(default=100)),
                ("font_name", models.CharField(default="Arial", max_length=40)),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("LEFT", "Esquerda"),
                            ("CENTER", "Centro"),
                            ("RIGHT", "Direita"),
                        ],
                        default="LEFT",
                        max_length=8,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_texts",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "idn_hotel_custom_text",
                "ordering": ["code"],
                "unique_together": {("hotel", "code")},
            },
        ),
        migrations.CreateModel(
            name="HotelGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="identity.enterprisegroup",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "idn_hotel_group",
                "ordering": ["sort_order"],
                "unique_together": {("hotel", "group")},
            },
        ),
    ]
