# Generated by Django 6.0.4 on 2026-07-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0006_hotel_address2_hotel_bg_color_hotel_country_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="license_contact",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
