# Generated by Django 6.0.7 on 2026-07-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "mdm_brand",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "mdm_tax",
                "ordering": ["code"],
            },
        ),
    ]
