# Generated by Django 6.0.7 on 2026-07-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Dinheiro"),
                            ("CARD", "Cartão"),
                            ("ROOM", "Conta Quarto"),
                            ("COMPANY", "Conta Empresa"),
                            ("VOUCHER", "Voucher"),
                            ("GIFTCARD", "Gift Card"),
                            ("CREDIT", "Crédito Cliente"),
                            ("MIXED", "Pagamento Misto"),
                            ("OTHER", "Outro"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="AOA", max_length=10)),
                ("allows_change", models.BooleanField(default=True)),
                ("allows_refund", models.BooleanField(default=True)),
                ("allows_partial", models.BooleanField(default=True)),
                ("allows_mixed", models.BooleanField(default=True)),
                ("allows_multicurrency", models.BooleanField(default=False)),
                (
                    "fee_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "mdm_payment_method",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
