# Generated by Django 6.0.7 on 2026-07-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0002_paymentmethod"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PROFORMA", "Pré-conta / Proforma"),
                            ("INVOICE", "Fatura"),
                            ("SIMPLIFIED", "Fatura Simplificada"),
                            ("CREDIT_NOTE", "Nota de Crédito"),
                            ("RECEIPT", "Recibo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prefix", models.CharField(default="FT", max_length=10)),
                ("year", models.PositiveIntegerField(default=2026)),
                ("current_number", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "mdm_document_series",
                "ordering": ["document_type", "code"],
            },
        ),
    ]
