# Generated by Django 6.0.4 on 2026-07-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0004_bank_country_currency_customer_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="vip_discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
