# Generated by Django 6.0.4 on 2026-07-12 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_reportdefinition"),
        ("mdm", "0005_customer_credit_limit_customer_is_vip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="buy_rate",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="currency",
            name="commission_charge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commission_currencies",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="commission_fixed",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="currency",
            name="commission_mode",
            field=models.CharField(
                choices=[
                    ("FIXED", "Comissão Fixa"),
                    ("PERCENT", "Comissão Percentual"),
                ],
                default="FIXED",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="commission_percent",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="currency",
            name="exchange_margin",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="currency",
            name="excluded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="currency",
            name="is_local",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="currency",
            name="margin",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="currency",
            name="margin_charge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="margin_currencies",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="paymaster_account",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="print_on_pos_docs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="currency",
            name="reference_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="sell_rate",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="currency",
            name="symbol_unicode",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="currency",
            name="rate_to_base",
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18),
        ),
        migrations.CreateModel(
            name="CurrencyRateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("changed_by", models.CharField(blank=True, max_length=120, null=True)),
                ("code", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=60)),
                (
                    "rate_to_base",
                    models.DecimalField(decimal_places=8, default=0, max_digits=18),
                ),
                (
                    "buy_rate",
                    models.DecimalField(decimal_places=8, default=0, max_digits=18),
                ),
                (
                    "sell_rate",
                    models.DecimalField(decimal_places=8, default=0, max_digits=18),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="mdm.currency",
                    ),
                ),
            ],
            options={
                "db_table": "mdm_currency_history",
                "ordering": ["changed_at"],
            },
        ),
    ]
