# Generated by Django 6.0.4 on 2026-07-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0006_currency_buy_rate_currency_commission_charge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="buy_rate",
            field=models.DecimalField(decimal_places=16, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name="currency",
            name="rate_to_base",
            field=models.DecimalField(decimal_places=16, default=1, max_digits=24),
        ),
        migrations.AlterField(
            model_name="currency",
            name="sell_rate",
            field=models.DecimalField(decimal_places=16, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name="currencyratehistory",
            name="buy_rate",
            field=models.DecimalField(decimal_places=16, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name="currencyratehistory",
            name="sell_rate",
            field=models.DecimalField(decimal_places=16, default=0, max_digits=24),
        ),
    ]
