# Generated by Django 6.0.4 on 2026-07-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0007_alter_currency_buy_rate_alter_currency_rate_to_base_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tax",
        ),
    ]
