# Generated by Django 6.0.4 on 2026-07-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_reportdefinition"),
        ("mdm", "0008_delete_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="accounting_account",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="allow_pickup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="ask_document_number",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="bank_transfer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="charge_to_room",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="close_only_zero_balance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="cross_selling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="current_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="direct_payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="document_model_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="document_type",
            field=models.CharField(
                choices=[("INVOICE", "Fatura"), ("RECEIPT", "Talão")],
                default="INVOICE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="external_device",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="external_interface",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="for_ems",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="for_fnb",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="for_pos",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="internal_consumption",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="internal_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internal_methods",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="opens_drawer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="other_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="pickup_alert_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="pickup_alert_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="pms_reference",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="prints_document",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="tip_from_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="tip_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tip_methods",
                to="inventory.item",
            ),
        ),
    ]
