# Generated by Django 6.0.4 on 2026-07-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0009_paymentmethod_abbreviation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="culture_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="language",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="language",
            name="is_mailing_default",
            field=models.BooleanField(default=False),
        ),
    ]
