# Generated by Django 6.0.4 on 2026-07-13 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0011_customer_birth_date_customer_block_reason_and_more"),
        ("pos", "0043_entityfieldrule_eventrequest_answered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="member_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="holders",
                to="pos.membercard",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="member_card_number",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
