# Generated by Django 6.0.4 on 2026-07-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0012_customer_member_card_customer_member_card_number"),
        ("pos", "0052_posticketline_served_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="account_number",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="address2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="birth_place",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="pos.distributionchannel",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="doc_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="doc_issue_place",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="doc_issued_by",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="doc_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="doc_valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="email2",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="fax",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="iata",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_supplier",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="language",
            field=models.CharField(default="pt-PT", max_length=10),
        ),
        migrations.AddField(
            model_name="customer",
            name="mobile",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="only_cash",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone2",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="position",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="pos.segment",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="signature_url",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="site",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="sub_segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="pos.subsegment",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="title",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name="CustomerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("NOTE", "Nota"),
                            ("SOCIAL", "Rede social"),
                            ("DOC", "Documento"),
                            ("LINK", "Ligação"),
                            ("AGREEMENT", "Acordo"),
                            ("BILLING", "Instrução de faturação"),
                            ("COMMISSION", "Comissão"),
                            ("CONSENT", "Consentimento"),
                            ("CHILD", "Criança"),
                            ("JOURNEY", "Guest journey"),
                            ("CUSTOM", "Campo personalizado"),
                            ("INFO", "Informação de secção"),
                        ],
                        max_length=12,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("created_by", models.CharField(blank=True, max_length=60, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="mdm.customer",
                    ),
                ),
            ],
            options={
                "db_table": "mdm_customer_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
