# Generated by Django 6.0.4 on 2026-07-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0013_customer_account_number_customer_address2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
