# Generated by Django 6.0.4 on 2026-07-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0014_customer_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="profile",
        ),
        migrations.AddField(
            model_name="customer",
            name="address3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="allow_cc_checkout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_address2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_city",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_country",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_postal",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="block_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="block_mode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="block_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="brand",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="cc_by",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="commission_code",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="commission_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limit_mode",
            field=models.CharField(default="Sem restrições", max_length=30),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limit_pos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limit_pos_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="distinction_program",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="district",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="einvoice_mode",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="financial_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="has_warnings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="include_mailings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="internal_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="internal_status",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="long_title",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="mailing_birthday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="mailing_events",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="mailing_general",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="mailing_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="minibar",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="online_checkin_pct",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="other_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="pay_tv",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_prefix",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="planning_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="plate",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="portal_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="pref_category",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="pref_complex",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="pref_discount",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="pref_discount_rule",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="pref_meal_type",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="pref_meals",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="pref_package",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="pref_pos_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="pref_price_list",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="pref_rest_table",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="pref_room",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="prefix",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="region",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="short_title",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="stat_aggregator",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="suggest_on_reservation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="suggestion_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="sync_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="video",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="vip_code",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="warning_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="withholding_tax",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
