# Generated by Django 6.0.4 on 2026-07-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0015_remove_customer_profile_customer_address3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="fax2",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="mobile2",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="site2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
