# Generated by Django 6.0.4 on 2026-07-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0016_customer_fax2_customer_mobile2_customer_site2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerrecord",
            name="kind",
            field=models.CharField(
                choices=[
                    ("NOTE", "Nota"),
                    ("SOCIAL", "Rede social"),
                    ("DOC", "Documento"),
                    ("LINK", "Ligação"),
                    ("AGREEMENT", "Acordo"),
                    ("BILLING", "Instrução de faturação"),
                    ("COMMISSION", "Comissão"),
                    ("CONSENT", "Consentimento"),
                    ("CHILD", "Criança"),
                    ("JOURNEY", "Guest journey"),
                    ("CUSTOM", "Campo personalizado"),
                    ("INFO", "Informação de secção"),
                    ("CARD", "Cartão de membro"),
                    ("SELCODE", "Código de seleção"),
                    ("LOG", "Log RGPD"),
                ],
                max_length=12,
            ),
        ),
    ]
