# Generated by Django 6.0.4 on 2026-07-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0017_alter_customerrecord_kind"),
        ("pos", "0061_posticketline_is_gift"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="newsletter_interests",
            field=models.ManyToManyField(
                blank=True, related_name="interested_customers", to="pos.selectioncode"
            ),
        ),
    ]
