# Generated by Django 6.0.4 on 2026-07-08 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftwareRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.CharField(max_length=50, unique=True)),
                (
                    "target_module",
                    models.CharField(
                        choices=[
                            ("POS_FRONTEND", "Frontend POS (React/Flutter)"),
                            ("POS_SERVICE", "Serviço Local POS (Spooler/Hardware)"),
                            ("BACKEND", "Servidor ERP (Django)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("release_date", models.DateTimeField()),
                ("release_notes", models.TextField(blank=True, null=True)),
                ("download_url", models.URLField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=255, null=True)),
                ("is_mandatory", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkstationUpdateStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pendente"),
                            ("Downloading", "A Transferir"),
                            ("Installed", "Instalado"),
                            ("Failed", "Falha na Instalação"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("last_checked", models.DateTimeField(auto_now=True)),
                ("error_log", models.TextField(blank=True, null=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eum.softwarerelease",
                    ),
                ),
                (
                    "workstation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_statuses",
                        to="identity.workstation",
                    ),
                ),
            ],
            options={
                "unique_together": {("workstation", "release")},
            },
        ),
    ]
