# Generated by Django 6.0.4 on 2026-07-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "journal_type",
                    models.CharField(
                        choices=[
                            ("SALES", "Diário de Vendas"),
                            ("PURCHASES", "Diário de Compras"),
                            ("CASH", "Diário de Caixa"),
                            ("BANK", "Diário de Banco"),
                            ("GENERAL", "Diário de Operações Diversas"),
                            ("OPENING", "Diário de Abertura"),
                        ],
                        default="GENERAL",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "acc_journal",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "account_class",
                    models.CharField(
                        choices=[
                            ("1", "Classe 1 — Meios Circulantes Financeiros"),
                            ("2", "Classe 2 — Terceiros"),
                            ("3", "Classe 3 — Existências"),
                            ("4", "Classe 4 — Imobilizações"),
                            ("5", "Classe 5 — Fundos Próprios"),
                            ("6", "Classe 6 — Proveitos e Ganhos por Natureza"),
                            ("7", "Classe 7 — Custos e Perdas por Natureza"),
                            ("8", "Classe 8 — Resultados"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Ativo"),
                            ("LIABILITY", "Passivo"),
                            ("EQUITY", "Fundos Próprios"),
                            ("INCOME", "Proveitos"),
                            ("EXPENSE", "Custos"),
                            ("RESULT", "Resultados"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_movement", models.BooleanField(default=True)),
                (
                    "normal_side",
                    models.CharField(
                        choices=[("D", "Devedora"), ("C", "Credora")],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "db_table": "acc_account",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=40)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "acc_period",
                "ordering": ["-start_date"],
                "unique_together": {("year", "name")},
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("entry_date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("POS", "POS/Vendas"),
                            ("PURCHASE", "Compras"),
                            ("TREASURY", "Tesouraria"),
                            ("OPENING", "Abertura"),
                            ("CLOSING", "Apuramento"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("POSTED", "Lançado"),
                            ("REVERSED", "Estornado"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="accounting.journal",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="accounting.fiscalperiod",
                    ),
                ),
            ],
            options={
                "db_table": "acc_entry",
                "ordering": ["-entry_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("cost_center", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="accounting.account",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "db_table": "acc_entry_line",
            },
        ),
    ]
