# Generated by Django 6.0.4 on 2026-08-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0007_hotel_license_contact"),
        ("mdm", "0018_customer_newsletter_interests"),
        ("pos", "0064_posuser_keyboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("label", models.CharField(default="A · Principal", max_length=60)),
                (
                    "payer_type",
                    models.CharField(
                        choices=[
                            ("GUEST", "Hóspede"),
                            ("COMPANY", "Empresa"),
                            ("AGENCY", "Agência"),
                            ("HOUSE", "Cortesia (casa)"),
                        ],
                        default="GUEST",
                        max_length=8,
                    ),
                ),
                ("payer_name", models.CharField(blank=True, max_length=200, null=True)),
                ("payer_nif", models.CharField(blank=True, max_length=30, null=True)),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Aberto"), ("CLOSED", "Fechado")],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fiscal_document_number",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
            ],
            options={
                "db_table": "pms_folio",
                "ordering": ["-is_primary", "opened_at"],
            },
        ),
        migrations.CreateModel(
            name="FolioCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("ROOM", "Alojamento"),
                            ("FNB", "F&B (POS)"),
                            ("LAUNDRY", "Lavandaria"),
                            ("MINIBAR", "Minibar"),
                            ("SPA", "Spa"),
                            ("TAX", "Taxa"),
                            ("MISC", "Diversos"),
                            ("PAYMENT", "Pagamento"),
                        ],
                        default="MISC",
                        max_length=8,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "source_reference",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("posted_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_void", models.BooleanField(default=False)),
                (
                    "void_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("voided_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "transferred_from",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("transferred_at", models.DateTimeField(blank=True, null=True)),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="pms.folio",
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversals",
                        to="pms.foliocharge",
                    ),
                ),
            ],
            options={
                "db_table": "pms_folio_charge",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RatePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("board", models.CharField(default="RO", max_length=10)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("min_nights", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pms_rate_plans",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_rate_plan",
                "ordering": ["room_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_guaranteed", models.BooleanField(default=False)),
                ("is_elastic", models.BooleanField(default=False)),
                ("group_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "other_entity",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("manager", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "default_prefix",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "default_reservation_type",
                    models.CharField(default="Normal", max_length=20),
                ),
                (
                    "default_voucher",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("arrival_until", models.DateField(blank=True, null=True)),
                ("departure_until", models.DateField(blank=True, null=True)),
                ("block_info", models.TextField(blank=True, null=True)),
                ("reservation_info", models.TextField(blank=True, null=True)),
                (
                    "release_method",
                    models.CharField(
                        choices=[("DATE", "Data"), ("DAYS", "Dias antes da chegada")],
                        default="DAYS",
                        max_length=6,
                    ),
                ),
                ("release_days", models.PositiveIntegerField(default=0)),
                (
                    "contract_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "default_channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pos.distributionchannel",
                    ),
                ),
                (
                    "default_segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pos.segment",
                    ),
                ),
                (
                    "default_subsegment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pos.subsegment",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pms_blocks",
                        to="identity.hotel",
                    ),
                ),
                (
                    "main_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pms_blocks_main",
                        to="mdm.customer",
                    ),
                ),
                (
                    "default_rate_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pms.rateplan",
                    ),
                ),
            ],
            options={
                "db_table": "pms_block",
                "ordering": ["-valid_from"],
                "unique_together": {("hotel", "code")},
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmation", models.CharField(max_length=30, unique=True)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("adults", models.PositiveIntegerField(default=1)),
                ("children", models.PositiveIntegerField(default=0)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_guaranteed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPTION", "Opção"),
                            ("BOOKED", "Reservada"),
                            ("CHECKED_IN", "Check-in"),
                            ("CHECKED_OUT", "Check-out"),
                            ("CANCELLED", "Cancelada"),
                            ("NO_SHOW", "No-show"),
                            ("WAITLIST", "Lista de Espera"),
                        ],
                        default="BOOKED",
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direto (receção)"),
                            ("ONLINE", "Online"),
                            ("BLOCK", "Bloco/Grupo"),
                        ],
                        default="DIRECT",
                        max_length=10,
                    ),
                ),
                ("voucher", models.CharField(blank=True, max_length=40, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="pms.block",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pos.distributionchannel",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pms_reservations",
                        to="mdm.customer",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pms_reservations",
                        to="identity.hotel",
                    ),
                ),
                (
                    "rate_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pms.rateplan",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pos.segment",
                    ),
                ),
                (
                    "sub_segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pos.subsegment",
                    ),
                ),
            ],
            options={
                "db_table": "pms_reservation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="folio",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folios",
                to="pms.reservation",
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VACANT_CLEAN", "Livre / Limpo"),
                            ("VACANT_DIRTY", "Livre / Por limpar"),
                            ("OCCUPIED", "Ocupado"),
                            ("OOO", "Fora de serviço"),
                        ],
                        default="VACANT_CLEAN",
                        max_length=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="identity.building",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="identity.floor",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pms_rooms",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_room",
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="pms.room",
            ),
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("capacity_adults", models.PositiveIntegerField(default=2)),
                ("capacity_children", models.PositiveIntegerField(default=0)),
                (
                    "base_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pms_room_types",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_room_type",
                "ordering": ["code"],
                "unique_together": {("hotel", "code")},
            },
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="pms.roomtype",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="pms.roomtype",
            ),
        ),
        migrations.AddField(
            model_name="rateplan",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_plans",
                to="pms.roomtype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("hotel", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="rateplan",
            unique_together={("hotel", "code")},
        ),
        migrations.CreateModel(
            name="BlockRoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("rooms_blocked", models.PositiveIntegerField(default=0)),
                (
                    "rate_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_types",
                        to="pms.block",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="pms.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "pms_block_room_type",
                "unique_together": {("block", "room_type", "date")},
            },
        ),
    ]
