# Generated by Django 6.0.4 on 2026-07-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Aberto"), ("CLOSED", "Fechado")],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "pms_folio",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="FolioCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("ROOM", "Alojamento"),
                            ("FNB", "F&B (POS)"),
                            ("TAX", "Taxa"),
                            ("MISC", "Diversos"),
                            ("PAYMENT", "Pagamento"),
                        ],
                        default="MISC",
                        max_length=8,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "source_reference",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("posted_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="pms.folio",
                    ),
                ),
            ],
            options={
                "db_table": "pms_folio_charge",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("document_id", models.CharField(blank=True, max_length=50, null=True)),
                ("tax_id", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                ("country", models.CharField(blank=True, max_length=60, null=True)),
                ("vip", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_guest",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmation", models.CharField(max_length=30, unique=True)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("adults", models.PositiveIntegerField(default=1)),
                ("children", models.PositiveIntegerField(default=0)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Reservada"),
                            ("CHECKED_IN", "Check-in"),
                            ("CHECKED_OUT", "Check-out"),
                            ("CANCELLED", "Cancelada"),
                            ("NO_SHOW", "No-show"),
                        ],
                        default="BOOKED",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="pms.guest",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_reservation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="folio",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folio",
                to="pms.reservation",
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                ("floor", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VACANT_CLEAN", "Livre / Limpo"),
                            ("VACANT_DIRTY", "Livre / Por limpar"),
                            ("OCCUPIED", "Ocupado"),
                            ("OOO", "Fora de serviço"),
                        ],
                        default="VACANT_CLEAN",
                        max_length=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_room",
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="pms.room",
            ),
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField(default=2)),
                (
                    "base_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_types",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_room_type",
                "unique_together": {("hotel", "code")},
            },
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="pms.roomtype",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="pms.roomtype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("hotel", "number")},
        ),
    ]
