# Generated by Django 6.0.4 on 2026-07-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="folio",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
