# Generated by Django 6.0.4 on 2026-08-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_code",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Pequeno Almoço"),
                            ("COFFEE_AM", "Coffee Break Manhã"),
                            ("LUNCH", "Almoço"),
                            ("COFFEE_PM", "Coffee Break Tarde"),
                            ("SNACK", "Lanche"),
                            ("DINNER", "Jantar"),
                            ("SUPPER", "Ceia"),
                            ("COCKTAIL_AM", "COCKTAIL MANHÃ"),
                            ("COCKTAIL_PM", "COCKTAIL TARDE"),
                        ],
                        max_length=15,
                    ),
                ),
                ("date", models.DateField()),
                ("adults", models.PositiveIntegerField(default=0)),
                ("children_1", models.PositiveIntegerField(default=0)),
                ("children_2", models.PositiveIntegerField(default=0)),
                ("children_3", models.PositiveIntegerField(default=0)),
                ("info", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plan_entries",
                        to="pms.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "pms_meal_plan_entry",
                "ordering": ["date", "meal_code"],
                "unique_together": {("reservation", "meal_code", "date")},
            },
        ),
    ]
