# Generated by Django 6.0.4 on 2026-09-25 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0002_mealplanentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "price_per_night",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("min_nights", models.PositiveIntegerField(blank=True, null=True)),
                ("is_bookable", models.BooleanField(blank=True, null=True)),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="pms.rateplan",
                    ),
                ),
            ],
            options={
                "db_table": "pms_rate_override",
                "ordering": ["date"],
                "unique_together": {("rate_plan", "date")},
            },
        ),
    ]
