# Generated by Django 6.0.4 on 2026-09-25 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0007_hotel_license_contact"),
        ("pms", "0003_rateoverride"),
    ]

    operations = [
        migrations.CreateModel(
            name="NightAuditRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit_date", models.DateField()),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                ("run_by", models.CharField(blank=True, max_length=100, null=True)),
                ("rooms_charged", models.PositiveIntegerField(default=0)),
                (
                    "total_posted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pms_night_audit_runs",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_night_audit_run",
                "ordering": ["-audit_date"],
                "unique_together": {("hotel", "audit_date")},
            },
        ),
    ]
