# Generated by Django 6.0.4 on 2026-07-10 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("pms", "0003_housekeepingtask_maintenanceorder_rateplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foliocharge",
            name="charge_type",
            field=models.CharField(
                choices=[
                    ("ROOM", "Alojamento"),
                    ("FNB", "F&B (POS)"),
                    ("LAUNDRY", "Lavandaria"),
                    ("MINIBAR", "Minibar"),
                    ("SPA", "Spa"),
                    ("TAX", "Taxa"),
                    ("MISC", "Diversos"),
                    ("PAYMENT", "Pagamento"),
                ],
                default="MISC",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="LaundryOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(blank=True, max_length=150, null=True)),
                ("description", models.CharField(max_length=255)),
                ("pieces", models.PositiveIntegerField(default=1)),
                ("express", models.BooleanField(default=False)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Recebida"),
                            ("PROCESSING", "Em lavagem"),
                            ("READY", "Pronta"),
                            ("DELIVERED", "Entregue"),
                        ],
                        default="RECEIVED",
                        max_length=12,
                    ),
                ),
                ("charged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laundry_orders",
                        to="identity.hotel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laundry_orders",
                        to="pms.room",
                    ),
                ),
            ],
            options={
                "db_table": "pms_laundry_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MinibarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minibar_items",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_minibar_item",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpaAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(blank=True, max_length=150, null=True)),
                ("service", models.CharField(max_length=120)),
                ("therapist", models.CharField(blank=True, max_length=100, null=True)),
                ("scheduled_for", models.DateTimeField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Marcada"),
                            ("DONE", "Realizada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="BOOKED",
                        max_length=10,
                    ),
                ),
                ("charged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spa_appointments",
                        to="identity.hotel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spa_appointments",
                        to="pms.room",
                    ),
                ),
            ],
            options={
                "db_table": "pms_spa_appointment",
                "ordering": ["scheduled_for"],
            },
        ),
    ]
