# Generated by Django 6.0.4 on 2026-09-25 22:41

import django.db.models.deletion
import pms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0007_hotel_license_contact"),
        ("mdm", "0018_customer_newsletter_interests"),
        ("pms", "0003_rateoverride"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
                (
                    "api_key",
                    models.CharField(
                        default=pms.models._rand_key, max_length=64, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("currency", models.CharField(default="AOA", max_length=10)),
                (
                    "deposit_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("payment_enabled", models.BooleanField(default=False)),
                (
                    "payment_provider",
                    models.CharField(
                        choices=[
                            ("SIMULATED", "Simulado (testes)"),
                            ("MULTICAIXA", "Multicaixa Express"),
                            ("EMIS", "EMIS GPO"),
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                        ],
                        default="SIMULATED",
                        max_length=20,
                    ),
                ),
                ("primary_color", models.CharField(default="#5C8891", max_length=10)),
                (
                    "welcome_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "cancellation_policy",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "custom_domain",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("logo_url", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "hero_image_url",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "min_advance_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_advance_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_settings",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_booking_settings",
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "ota_type",
                    models.CharField(
                        choices=[
                            ("BOOKING", "Booking.com"),
                            ("EXPEDIA", "Expedia"),
                            ("AIRBNB", "Airbnb"),
                            ("AGODA", "Agoda"),
                            ("HOTELS", "Hotels.com"),
                            ("TRIVAGO", "Trivago"),
                            ("GOOGLE", "Google Hotels"),
                            ("OTHER", "Outro"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("property_id", models.CharField(blank=True, max_length=80, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISCONNECTED", "Desligado"),
                            ("PENDING", "Credenciais pendentes"),
                            ("CONNECTED", "Ligado"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pms_channels",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_channel",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChannelSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("PUSH", "Enviado"), ("PULL", "Recebido")],
                        default="PUSH",
                        max_length=4,
                    ),
                ),
                ("event", models.CharField(default="availability", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "Sucesso"),
                            ("ERROR", "Erro"),
                            ("SKIPPED", "Sem credenciais"),
                        ],
                        default="SKIPPED",
                        max_length=8,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=500, null=True)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="pms.channel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_channel_sync_log",
                "ordering": ["-synced_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whatsapp_phone_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "whatsapp_business_account_id",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "welcome_message",
                    models.TextField(
                        default="Olá! Posso ajudar a verificar disponibilidade e criar uma reserva. Como posso ajudar?"
                    ),
                ),
                (
                    "hotel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_settings",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_chatbot_settings",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("event_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=150, null=True)),
                ("expected_guests", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INQUIRY", "Pedido"),
                            ("CONFIRMED", "Confirmado"),
                            ("CANCELLED", "Cancelado"),
                            ("COMPLETED", "Concluído"),
                        ],
                        default="INQUIRY",
                        max_length=10,
                    ),
                ),
                (
                    "estimated_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pms_events",
                        to="mdm.customer",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pms_events",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_event",
                "ordering": ["event_date"],
            },
        ),
    ]
