# Generated by Django 6.0.4 on 2026-09-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0003_rateoverride"),
        ("identity", "0007_hotel_license_contact"),
        ("mdm", "0018_customer_newsletter_interests"),
    ]

    operations = [
        migrations.CreateModel(
            name="LostFoundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("found_location", models.CharField(blank=True, max_length=150, null=True)),
                ("found_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FOUND", "Encontrado"),
                            ("CLAIMED", "Reclamado"),
                            ("DISPOSED", "Descartado"),
                        ],
                        default="FOUND",
                        max_length=10,
                    ),
                ),
                ("claimed_by", models.CharField(blank=True, max_length=150, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="mdm.customer",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pms_lost_found_items",
                        to="identity.hotel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pms.room",
                    ),
                ),
            ],
            options={
                "db_table": "pms_lost_found_item",
                "ordering": ["-found_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HousekeepingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("assigned_to", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("LOW", "Baixa"), ("NORMAL", "Normal"), ("HIGH", "Alta")],
                        default="NORMAL",
                        max_length=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("IN_PROGRESS", "Em curso"),
                            ("DONE", "Concluída"),
                        ],
                        default="PENDING",
                        max_length=11,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pms_tasks",
                        to="identity.hotel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pms.room",
                    ),
                ),
            ],
            options={
                "db_table": "pms_housekeeping_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhoneDirectoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("extension", models.CharField(blank=True, max_length=20, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pms_phone_directory",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_phone_directory_entry",
                "ordering": ["name"],
            },
        ),
    ]
