# Generated by Django 6.0.4 on 2026-07-10 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("pms", "0004_alter_foliocharge_charge_type_laundryorder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Empresa"),
                            ("AGENCY", "Agência de viagens"),
                        ],
                        default="COMPANY",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tax_id", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=120, null=True)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("payment_terms_days", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate_accounts",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_corporate_account",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NightAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_date", models.DateField()),
                ("rooms_charged", models.PositiveIntegerField(default=0)),
                (
                    "room_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("arrivals", models.PositiveIntegerField(default=0)),
                ("departures", models.PositiveIntegerField(default=0)),
                ("in_house", models.PositiveIntegerField(default=0)),
                ("run_by", models.CharField(blank=True, max_length=100, null=True)),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="night_audits",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_night_audit",
                "ordering": ["-business_date"],
                "unique_together": {("hotel", "business_date")},
            },
        ),
    ]
