# Generated by Django 6.0.4 on 2026-07-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("pms", "0005_corporateaccount_nightauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="online_ref",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="source",
            field=models.CharField(default="DIRECT", max_length=10),
        ),
        migrations.CreateModel(
            name="BookingSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("slug", models.CharField(max_length=60, unique=True)),
                ("api_key", models.CharField(max_length=64, unique=True)),
                ("currency", models.CharField(default="AOA", max_length=8)),
                ("languages", models.CharField(default="pt", max_length=60)),
                ("primary_color", models.CharField(default="#1e3f66", max_length=20)),
                ("logo_url", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "hero_image_url",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "welcome_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "deposit_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cancellation_policy",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_setting",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_booking_setting",
            },
        ),
    ]
