# Generated by Django 6.0.4 on 2026-07-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0006_reservation_online_ref_reservation_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingsetting",
            name="custom_domain",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
