# Generated by Django 6.0.4 on 2026-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0006_bookingsettings_channel_channelsynclog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="color_tag",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="Cor"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="eta",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de chegada prevista"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="etd",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de saída prevista"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="lock_room",
            field=models.BooleanField(
                default=False, verbose_name="Não mudar de quarto"
            ),
        ),
    ]
