# Generated by Django 6.0.4 on 2026-09-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0007_reservation_color_tag_reservation_eta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="housekeepingtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("CLEANING", "Limpeza"),
                    ("MAINTENANCE", "Manutenção"),
                    ("OTHER", "Outra"),
                ],
                default="CLEANING",
                max_length=12,
                verbose_name="Tipo de tarefa",
            ),
        ),
    ]
