# Generated by Django 6.0.4 on 2026-07-11 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("pms", "0007_bookingsetting_custom_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("BOOKING", "Booking.com"),
                            ("EXPEDIA", "Expedia"),
                            ("AIRBNB", "Airbnb"),
                            ("AGODA", "Agoda"),
                            ("HOTELS", "Hotels.com"),
                            ("TRIVAGO", "Trivago"),
                            ("GOOGLE", "Google Hotels"),
                            ("OTHER", "Outro"),
                        ],
                        default="BOOKING",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("property_id", models.CharField(blank=True, max_length=80, null=True)),
                ("api_key", models.CharField(blank=True, max_length=200, null=True)),
                ("currency", models.CharField(default="AOA", max_length=8)),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, default=15, max_digits=5),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "Ligado"),
                            ("ERROR", "Erro"),
                            ("DISABLED", "Desativado"),
                        ],
                        default="DISABLED",
                        max_length=10,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_channel",
                "ordering": ["provider"],
            },
        ),
        migrations.CreateModel(
            name="ChannelSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("PUSH", "Enviado (disponibilidade/tarifas)"),
                            ("PULL", "Recebido (reservas)"),
                        ],
                        max_length=6,
                    ),
                ),
                ("event", models.CharField(max_length=60)),
                ("summary", models.CharField(blank=True, max_length=300, null=True)),
                ("status", models.CharField(default="OK", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="pms.channel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_channel_sync_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChannelRoomMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_room_code", models.CharField(max_length=80)),
                (
                    "remote_rate_code",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_maps",
                        to="pms.channel",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_maps",
                        to="pms.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "pms_channel_room_map",
                "unique_together": {("channel", "room_type")},
            },
        ),
    ]
