# Generated by Django 6.0.4 on 2026-07-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0008_channel_channelsynclog_channelroommap"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="online_checkin",
            field=models.BooleanField(default=False),
        ),
    ]
