# Generated by Django 6.0.4 on 2026-10-01 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0008_housekeepingtask_task_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="SIMULATED", max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="AOA", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PAID", "Pago"),
                            ("FAILED", "Falhado"),
                            ("REFUNDED", "Devolvido"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GATEWAY", "Pagamento online"),
                            ("TRANSFER", "Transferência bancária"),
                            ("CASH", "Numerário"),
                            ("CARD", "Cartão"),
                            ("OTHER", "Outro"),
                        ],
                        default="GATEWAY",
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Referência do pagamento",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "confirmed_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("posted_to_folio", models.BooleanField(default=False)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_payments",
                        to="pms.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "pms_booking_payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChannelRoomMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ota_room_id",
                    models.CharField(max_length=80, verbose_name="ID do quarto na OTA"),
                ),
                (
                    "ota_rate_id",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="ID da tarifa na OTA",
                    ),
                ),
                (
                    "max_rooms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Limite de quartos no canal"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_maps",
                        to="pms.channel",
                    ),
                ),
                (
                    "rate_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="channel_maps",
                        to="pms.rateplan",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_maps",
                        to="pms.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "pms_channel_room_map",
                "ordering": ["channel", "room_type"],
                "unique_together": {
                    ("channel", "ota_room_id"),
                    ("channel", "room_type"),
                },
            },
        ),
    ]
