# Generated by Django 6.0.4 on 2026-07-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0009_reservation_online_checkin"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingsetting",
            name="payment_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookingsetting",
            name="payment_key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bookingsetting",
            name="payment_provider",
            field=models.CharField(default="SIMULATED", max_length=12),
        ),
        migrations.CreateModel(
            name="BookingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("SIMULATED", "Simulado"),
                            ("MULTICAIXA", "Multicaixa Express"),
                            ("EMIS", "EMIS GPO"),
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                        ],
                        default="SIMULATED",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PAID", "Pago"),
                            ("FAILED", "Falhou"),
                            ("REFUNDED", "Reembolsado"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(max_length=40, unique=True)),
                (
                    "gateway_ref",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="pms.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "pms_booking_payment",
                "ordering": ["-created_at"],
            },
        ),
    ]
