# Generated by Django 6.0.4 on 2026-10-02 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0009_bookingpayment_channelroommap"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationFixedCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("ROOM", "Alojamento"),
                            ("FNB", "F&B (POS)"),
                            ("LAUNDRY", "Lavandaria"),
                            ("MINIBAR", "Minibar"),
                            ("SPA", "Spa"),
                            ("TAX", "Taxa"),
                            ("MISC", "Diversos"),
                            ("PAYMENT", "Pagamento"),
                        ],
                        default="MISC",
                        max_length=8,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "per_night",
                    models.BooleanField(default=True, verbose_name="Por noite"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_charges",
                        to="pms.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "pms_reservation_fixed_charge",
                "ordering": ["description"],
            },
        ),
    ]
