# Generated by Django 6.0.4 on 2026-10-02 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0007_hotel_license_contact"),
        ("pms", "0010_reservationfixedcharge"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pms_room_attributes",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pms_room_attribute",
                "ordering": ["name"],
                "unique_together": {("hotel", "code")},
            },
        ),
        migrations.AddField(
            model_name="room",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="rooms",
                to="pms.roomattribute",
                verbose_name="Características",
            ),
        ),
    ]
