# Generated by Django 6.0.4 on 2026-07-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0010_bookingsetting_payment_enabled_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="folio",
            options={"ordering": ["-is_primary", "opened_at"]},
        ),
        migrations.AddField(
            model_name="folio",
            name="is_primary",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="folio",
            name="label",
            field=models.CharField(default="A · Principal", max_length=60),
        ),
        migrations.AddField(
            model_name="folio",
            name="payer_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="folio",
            name="payer_nif",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="folio",
            name="payer_type",
            field=models.CharField(
                choices=[
                    ("GUEST", "Hóspede"),
                    ("COMPANY", "Empresa"),
                    ("AGENCY", "Agência"),
                    ("HOUSE", "Cortesia (casa)"),
                ],
                default="GUEST",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="foliocharge",
            name="is_void",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="foliocharge",
            name="reversal_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="pms.foliocharge",
            ),
        ),
        migrations.AddField(
            model_name="foliocharge",
            name="transferred_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foliocharge",
            name="transferred_from",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="foliocharge",
            name="void_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="foliocharge",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foliocharge",
            name="voided_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="folio",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folios",
                to="pms.reservation",
            ),
        ),
    ]
