# Generated by Django 6.0.4 on 2026-10-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0011_roomattribute_room_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotsettings",
            name="bridge_token",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Chave do serviço de ponte",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="bridge_url",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Endereço do serviço de ponte",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="connected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="connected_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="connection_mode",
            field=models.CharField(
                choices=[
                    ("OFFICIAL", "API oficial (Meta Cloud API)"),
                    ("BRIDGE", "API não oficial (ponte WhatsApp Web)"),
                ],
                default="OFFICIAL",
                max_length=10,
                verbose_name="Forma de ligação",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="pairing_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="pairing_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="pairing_method",
            field=models.CharField(
                choices=[
                    ("QR", "Ler QR Code com o telemóvel"),
                    ("PHONE", "Código para o número de telemóvel"),
                ],
                default="QR",
                max_length=6,
                verbose_name="Como emparelhar",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="qr_payload",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="session_message",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="session_status",
            field=models.CharField(
                choices=[
                    ("DISCONNECTED", "Desligado"),
                    ("PAIRING", "À espera de emparelhar"),
                    ("CONNECTED", "Ligado"),
                    ("ERROR", "Erro"),
                ],
                default="DISCONNECTED",
                max_length=14,
            ),
        ),
    ]
