# Generated by Django 6.0.7 on 2026-07-08 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("inventory", "0001_initial"),
        ("mdm", "0002_paymentmethod"),
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "outlet_type",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "Restaurante"),
                            ("BAR", "Bar"),
                            ("POOL_BAR", "Pool Bar"),
                            ("COFFEE", "Coffee Shop"),
                            ("ROOM_SERVICE", "Room Service"),
                            ("MINIBAR", "Minibar"),
                            ("SPA", "Spa"),
                            ("SHOP", "Loja"),
                            ("BANQUET", "Banquetes"),
                            ("OTHER", "Outro"),
                        ],
                        default="RESTAURANT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlets",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "pos_outlet",
            },
        ),
        migrations.CreateModel(
            name="OutletPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="pos.outlet",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlet_availability",
                        to="mdm.paymentmethod",
                    ),
                ),
            ],
            options={
                "db_table": "pos_outlet_payment_method",
                "ordering": ["sort_order"],
                "unique_together": {("outlet", "payment_method")},
            },
        ),
        migrations.CreateModel(
            name="POSProductConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "pos_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preço específico no POS. Vazio = usa o preço de venda do artigo.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "pos_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "button_color",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_configs",
                        to="inventory.item",
                    ),
                ),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_configs",
                        to="pos.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "pos_product_config",
                "ordering": ["sort_order"],
                "unique_together": {("outlet", "item")},
            },
        ),
    ]
