# Generated by Django 6.0.7 on 2026-07-08 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_outlet_outletpaymentmethod_posproductconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terminal_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("operator_name", models.CharField(max_length=100)),
                (
                    "opening_float",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("opened_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Aberta"), ("CLOSED", "Fechada")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                (
                    "counted_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("closing_notes", models.TextField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_sessions",
                        to="pos.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "pos_cash_session",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("SANGRIA", "Sangria"),
                            ("REFORCO", "Reforço"),
                            ("ENTRADA", "Entrada Manual"),
                            ("SAIDA", "Saída Manual"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="pos.cashsession",
                    ),
                ),
            ],
            options={
                "db_table": "pos_cash_movement",
                "ordering": ["created_at"],
            },
        ),
    ]
