# Generated by Django 6.0.7 on 2026-07-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("mdm", "0002_paymentmethod"),
        ("pos", "0003_cashsession_cashmovement"),
    ]

    operations = [
        migrations.CreateModel(
            name="POSTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone", models.CharField(blank=True, max_length=50, null=True)),
                ("table_number", models.CharField(max_length=20)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("seats", models.PositiveIntegerField(default=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FREE", "Livre"),
                            ("OCCUPIED", "Ocupada"),
                            ("RESERVED", "Reservada"),
                            ("DIRTY", "Por limpar"),
                        ],
                        default="FREE",
                        max_length=10,
                    ),
                ),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="pos.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "pos_table_v2",
                "unique_together": {("outlet", "table_number")},
            },
        ),
        migrations.CreateModel(
            name="POSTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.CharField(max_length=30, unique=True)),
                ("operator_name", models.CharField(max_length=100)),
                ("guests", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberta"),
                            ("PAID", "Paga"),
                            ("VOID", "Anulada"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cash_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="pos.cashsession",
                    ),
                ),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="pos.outlet",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="pos.postable",
                    ),
                ),
            ],
            options={
                "db_table": "pos_ticket",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="POSTicketLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_ticket_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pos.posticket",
                    ),
                ),
            ],
            options={
                "db_table": "pos_ticket_line",
            },
        ),
        migrations.CreateModel(
            name="POSTicketPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "change_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_payments",
                        to="mdm.paymentmethod",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="pos.posticket",
                    ),
                ),
            ],
            options={
                "db_table": "pos_ticket_payment",
            },
        ),
    ]
