# Generated by Django 6.0.7 on 2026-07-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0004_postable_posticket_posticketline_posticketpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="posproductconfig",
            name="kds_station",
            field=models.CharField(
                choices=[
                    ("KITCHEN", "Cozinha"),
                    ("BAR", "Bar"),
                    ("PASTRY", "Pastelaria"),
                    ("NONE", "Sem produção"),
                ],
                default="KITCHEN",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="posticketline",
            name="fired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posticketline",
            name="kds_station",
            field=models.CharField(default="KITCHEN", max_length=10),
        ),
        migrations.AddField(
            model_name="posticketline",
            name="kds_status",
            field=models.CharField(
                choices=[
                    ("NEW", "Novo"),
                    ("FIRED", "Enviado"),
                    ("PREPARING", "Em Preparação"),
                    ("READY", "Pronto"),
                    ("SERVED", "Servido"),
                ],
                default="NEW",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="posticketline",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="posticketline",
            name="ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
