# Generated by Django 6.0.7 on 2026-07-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0003_documentseries"),
        ("pos", "0005_posproductconfig_kds_station_posticketline_fired_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="POSDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=20)),
                ("number", models.PositiveIntegerField()),
                ("full_number", models.CharField(max_length=40, unique=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "customer_tax_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ISSUED", "Emitido"), ("VOID", "Anulado")],
                        default="ISSUED",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="mdm.documentseries",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="pos.posticket",
                    ),
                ),
            ],
            options={
                "db_table": "pos_document",
                "ordering": ["-issued_at"],
            },
        ),
    ]
