# Generated by Django 6.0.7 on 2026-07-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0006_posdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="POSAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TICKET_OPEN", "Ticket aberto"),
                            ("LINE_ADD", "Linha adicionada"),
                            ("LINE_VOID", "Linha removida"),
                            ("KITCHEN_FIRE", "Enviado p/ cozinha"),
                            ("KDS_ADVANCE", "Estado de produção"),
                            ("PAYMENT", "Pagamento"),
                            ("DOC_ISSUE", "Documento emitido"),
                            ("DOC_VOID", "Documento anulado"),
                            ("TICKET_VOID", "Ticket anulado"),
                            ("CASH_OPEN", "Abertura de caixa"),
                            ("CASH_MOVE", "Movimento de caixa"),
                            ("CASH_CLOSE", "Fecho de caixa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "operator_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "terminal_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reference", models.CharField(blank=True, max_length=60, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("old_value", models.CharField(blank=True, max_length=100, null=True)),
                ("new_value", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="pos.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "pos_audit_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
