# Generated by Django 6.0.7 on 2026-07-09 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0007_posauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="posticket",
            name="client_uuid",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("KITCHEN", "Comanda Cozinha"),
                            ("BAR", "Comanda Bar"),
                            ("PASTRY", "Comanda Pastelaria"),
                            ("RECEIPT", "Talão"),
                            ("INVOICE", "Fatura"),
                            ("DRAWER", "Abrir Gaveta"),
                        ],
                        max_length=10,
                    ),
                ),
                ("target", models.CharField(blank=True, max_length=60, null=True)),
                ("title", models.CharField(max_length=120)),
                ("content", models.TextField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=60, null=True)),
                ("copies", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Em fila"),
                            ("PRINTED", "Impresso"),
                            ("FAILED", "Falhou"),
                            ("CANCELED", "Cancelado"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_jobs",
                        to="pos.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "pos_print_job",
                "ordering": ["-created_at"],
            },
        ),
    ]
