# Generated by Django 6.0.4 on 2026-07-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0008_posticket_client_uuid_printjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pos_gift_card",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="posticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Aberta"),
                    ("SUSPENDED", "Suspensa"),
                    ("PAID", "Paga"),
                    ("REFUNDED", "Estornada"),
                    ("VOID", "Anulada"),
                ],
                default="OPEN",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="POSLineModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price_delta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifiers",
                        to="pos.posticketline",
                    ),
                ),
            ],
            options={
                "db_table": "pos_line_modifier",
            },
        ),
        migrations.CreateModel(
            name="POSReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                ("party_size", models.PositiveIntegerField(default=2)),
                ("reserved_for", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Reservada"),
                            ("SEATED", "Sentada"),
                            ("CANCELLED", "Cancelada"),
                            ("NO_SHOW", "No-show"),
                        ],
                        default="BOOKED",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="pos.outlet",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="pos.postable",
                    ),
                ),
            ],
            options={
                "db_table": "pos_reservation",
                "ordering": ["reserved_for"],
            },
        ),
    ]
