# Generated by Django 6.0.4 on 2026-07-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0009_giftcard_alter_posticket_status_poslinemodifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postable",
            name="pos_x",
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name="postable",
            name="pos_y",
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name="postable",
            name="shape",
            field=models.CharField(
                choices=[("SQUARE", "Quadrada"), ("ROUND", "Redonda")],
                default="SQUARE",
                max_length=8,
            ),
        ),
    ]
