# Generated by Django 6.0.4 on 2026-07-09 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_pricelist_item_allow_fraction_item_barcode_and_more"),
        ("pos", "0010_postable_pos_x_postable_pos_y_postable_shape"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlet",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outlets",
                to="inventory.pricelist",
            ),
        ),
    ]
