# Generated by Django 6.0.4 on 2026-07-09 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_stockmovement"),
        ("pos", "0011_outlet_price_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlet",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outlets",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="posticket",
            name="stock_consumed",
            field=models.BooleanField(default=False),
        ),
    ]
