# Generated by Django 6.0.4 on 2026-07-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("pos", "0012_outlet_warehouse_posticket_stock_consumed"),
    ]

    operations = [
        migrations.AddField(
            model_name="posticket",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posticket",
            name="delivered_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="posticket",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("NONE", "N/A"),
                    ("PENDING", "Por despachar"),
                    ("DISPATCHED", "Despachado"),
                    ("DELIVERED", "Entregue"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="posticket",
            name="dest_kind",
            field=models.CharField(
                choices=[
                    ("TABLE", "Mesa"),
                    ("ROOM", "Quarto"),
                    ("DESTINATION", "Destino"),
                ],
                default="TABLE",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="posticket",
            name="dest_label",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="posticket",
            name="dest_note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="posticket",
            name="dest_priority",
            field=models.CharField(default="NORMAL", max_length=8),
        ),
        migrations.AddField(
            model_name="posticket",
            name="dest_ref",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="posticket",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ServiceDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "dtype",
                    models.CharField(
                        choices=[
                            ("POOL", "Piscina"),
                            ("BEACH", "Praia"),
                            ("SPA", "Spa"),
                            ("GYM", "Ginásio"),
                            ("EVENT", "Evento"),
                            ("CONFERENCE", "Sala de Conferência"),
                            ("CABANA", "Cabana"),
                            ("LOUNGE", "Lounge"),
                            ("LOBBY", "Lobby"),
                            ("ROOFTOP", "Rooftop"),
                            ("TERRACE", "Terraço"),
                            ("GARDEN", "Jardim"),
                            ("GOLF", "Campo de Golfe"),
                            ("TENNIS", "Campo de Ténis"),
                            ("VIP", "Zona VIP"),
                            ("OFFICE", "Escritório"),
                            ("OTHER", "Outro"),
                        ],
                        default="OTHER",
                        max_length=12,
                    ),
                ),
                ("zone", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "location_detail",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "responsible",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("eta_minutes", models.PositiveIntegerField(default=15)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Baixa"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "Alta"),
                            ("URGENT", "Urgente"),
                        ],
                        default="NORMAL",
                        max_length=8,
                    ),
                ),
                ("open_time", models.CharField(blank=True, max_length=5, null=True)),
                ("close_time", models.CharField(blank=True, max_length=5, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_destinations",
                        to="identity.hotel",
                    ),
                ),
                (
                    "outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_destinations",
                        to="pos.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "pos_service_destination",
                "ordering": ["dtype", "name"],
            },
        ),
    ]
