# Generated by Django 6.0.4 on 2026-07-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0013_posticket_delivered_at_posticket_delivered_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postable",
            name="cost_center",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="postable",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postable",
            name="max_capacity",
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name="postable",
            name="recommended_capacity",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="postable",
            name="shape",
            field=models.CharField(
                choices=[
                    ("SQUARE", "Quadrada"),
                    ("ROUND", "Redonda"),
                    ("RECT", "Retangular"),
                    ("BAR", "Balcão"),
                    ("SOFA", "Sofá"),
                ],
                default="SQUARE",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="postable",
            name="status",
            field=models.CharField(
                choices=[
                    ("FREE", "Livre"),
                    ("RESERVED", "Reservada"),
                    ("OCCUPIED", "Ocupada"),
                    ("DIRTY", "Limpeza"),
                    ("BLOCKED", "Bloqueada"),
                    ("MAINTENANCE", "Manutenção"),
                ],
                default="FREE",
                max_length=12,
            ),
        ),
    ]
