# Generated by Django 6.0.4 on 2026-07-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0014_postable_cost_center_postable_is_vip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posreservation",
            name="preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sem preferência"),
                    ("WINDOW", "Janela"),
                    ("TERRACE", "Terraço"),
                    ("VIP", "VIP"),
                    ("NON_SMOKING", "Não fumador"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="posreservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Confirmada"),
                    ("ARRIVED", "Chegada"),
                    ("SEATED", "Sentada"),
                    ("CANCELLED", "Cancelada"),
                    ("NO_SHOW", "No-show"),
                ],
                default="BOOKED",
                max_length=10,
            ),
        ),
    ]
