# Generated by Django 6.0.4 on 2026-07-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0015_posreservation_preference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posticket",
            name="adults",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="posticket",
            name="children",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="posticket",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="posticket",
            name="customer_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="posticket",
            name="customer_tax_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
