# Generated by Django 6.0.4 on 2026-07-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0017_postablegroup_postable_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="postable",
            name="vip_discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="posticket",
            name="discount_authorized_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="posticket",
            name="discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
