# Generated by Django 6.0.4 on 2026-07-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0018_postable_vip_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posticketline",
            name="is_void",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="posticketline",
            name="kds_ack_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posticketline",
            name="void_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="posticketline",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="posticketline",
            name="kds_status",
            field=models.CharField(
                choices=[
                    ("NEW", "Novo"),
                    ("FIRED", "Enviado"),
                    ("PREPARING", "Em Preparação"),
                    ("READY", "Pronto"),
                    ("SERVED", "Servido"),
                    ("CANCELLED", "ANULADO"),
                ],
                default="NEW",
                max_length=10,
            ),
        ),
    ]
