# Generated by Django 6.0.4 on 2026-07-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_reportdefinition"),
        ("pos", "0019_posticketline_is_void_posticketline_kds_ack_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_id", models.CharField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "description",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("right_id", models.PositiveIntegerField(default=0)),
                ("text_key", models.CharField(blank=True, max_length=40, null=True)),
                ("menu", models.CharField(blank=True, max_length=60, null=True)),
                ("license_key", models.CharField(blank=True, max_length=40, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("show_in_menu", models.BooleanField(default=True)),
                ("show_on_desktop", models.BooleanField(default=False)),
                ("is_iframe", models.BooleanField(default=False)),
                ("is_external_window", models.BooleanField(default=False)),
                ("is_widget", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "pos_module",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PosParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BOOL", "Sim/Não"),
                            ("INT", "Número"),
                            ("TEXT", "Texto"),
                            ("CHOICE", "Escolha"),
                        ],
                        default="BOOL",
                        max_length=8,
                    ),
                ),
                ("group", models.CharField(default="Geral", max_length=40)),
                ("choices", models.JSONField(blank=True, default=list)),
                ("default", models.CharField(blank=True, max_length=120, null=True)),
                ("help_text", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "db_table": "pos_parameter",
                "ordering": ["group", "number"],
            },
        ),
        migrations.CreateModel(
            name="PosTerminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "terminal_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("VIRTUAL", "Virtual"),
                            ("MOBILE", "Portátil"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminals",
                        to="pos.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "pos_terminal",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TerminalHardware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=80)),
                (
                    "hw_type",
                    models.CharField(
                        choices=[
                            ("DRAWER", "Gaveta"),
                            ("SCALE", "Balança"),
                            ("SCANNER", "Leitor de códigos"),
                            ("DISPLAY", "Display de cliente"),
                            ("CARD", "Terminal bancário"),
                            ("OTHER", "Outro"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("port", models.CharField(blank=True, max_length=40, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardware",
                        to="pos.posterminal",
                    ),
                ),
            ],
            options={
                "db_table": "pos_terminal_hardware",
            },
        ),
        migrations.CreateModel(
            name="TerminalPrinter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("TERMINAL", "Terminal"),
                            ("SERVER", "Servidor"),
                            ("NETWORK", "Rede"),
                        ],
                        default="TERMINAL",
                        max_length=10,
                    ),
                ),
                ("one_item_per_ticket", models.BooleanField(default=False)),
                ("kds_monitor", models.CharField(blank=True, max_length=60, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminals",
                        to="inventory.printer",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="printers",
                        to="pos.posterminal",
                    ),
                ),
            ],
            options={
                "db_table": "pos_terminal_printer",
                "unique_together": {("terminal", "printer")},
            },
        ),
    ]
