# Generated by Django 6.0.4 on 2026-07-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0002_loyaltyprogram_loyaltytier"),
        ("inventory", "0010_reportdefinition"),
        ("pos", "0020_posmodule_posparameter_posterminal_terminalhardware_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postable",
            name="color",
            field=models.CharField(default="#0f8b8d", max_length=20),
        ),
        migrations.AddField(
            model_name="postable",
            name="height",
            field=models.PositiveIntegerField(default=110),
        ),
        migrations.AddField(
            model_name="postable",
            name="max_seats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postable",
            name="min_seats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postable",
            name="online_reservation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postable",
            name="preferred_seats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postable",
            name="text_color",
            field=models.CharField(default="#ffffff", max_length=20),
        ),
        migrations.AddField(
            model_name="postable",
            name="width",
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.CreateModel(
            name="PosSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("price_level", models.PositiveSmallIntegerField(default=1)),
                ("seats", models.PositiveIntegerField(default=0)),
                ("keyboard", models.CharField(blank=True, max_length=60, null=True)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("map_bg_color", models.CharField(default="#fdeef0", max_length=20)),
                ("map_text_color", models.CharField(default="#ffffff", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "happy_hour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sectors",
                        to="commercial.promotion",
                    ),
                ),
                (
                    "outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sectors",
                        to="pos.outlet",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sectors",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "pos_sector",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="postable",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tables",
                to="pos.possector",
            ),
        ),
    ]
