# Generated by Django 6.0.4 on 2026-07-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0021_postable_color_postable_height_postable_max_seats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posparameter",
            name="scope",
            field=models.CharField(
                choices=[
                    ("GLOBAL", "Sistema"),
                    ("TERMINAL", "Terminal"),
                    ("SECTOR", "Setor"),
                ],
                default="TERMINAL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="posparameter",
            name="value",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
