# Generated by Django 6.0.4 on 2026-07-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_reportdefinition"),
        ("pos", "0022_posparameter_scope_posparameter_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosKeyboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=80)),
                ("price_level", models.PositiveSmallIntegerField(default=1)),
                ("cols", models.PositiveSmallIntegerField(default=4)),
                ("rows", models.PositiveSmallIntegerField(default=4)),
                ("show_codes", models.BooleanField(default=False)),
                ("show_prices", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pos_keyboard",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="PosKeyboardKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PAGE", "Página"),
                            ("FOLDER", "Pasta"),
                            ("ITEM", "Artigo"),
                        ],
                        default="FOLDER",
                        max_length=6,
                    ),
                ),
                ("label", models.CharField(max_length=60)),
                ("color", models.CharField(default="#1565c0", max_length=20)),
                ("text_color", models.CharField(default="#ffffff", max_length=20)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("span", models.PositiveSmallIntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyboard_keys",
                        to="inventory.item",
                    ),
                ),
                (
                    "keyboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="pos.poskeyboard",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="pos.poskeyboardkey",
                    ),
                ),
            ],
            options={
                "db_table": "pos_keyboard_key",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
