# Generated by Django 6.0.4 on 2026-07-12 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0023_poskeyboard_poskeyboardkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("color", models.CharField(default="#0080FF", max_length=20)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pos_time_band",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="TimeBandSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_from", models.TimeField()),
                ("time_to", models.TimeField()),
                (
                    "band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="pos.timeband",
                    ),
                ),
            ],
            options={
                "db_table": "pos_time_band_slot",
                "ordering": ["time_from"],
            },
        ),
    ]
