# Generated by Django 6.0.4 on 2026-07-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0024_timeband_timebandslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pos_schedule",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PosRight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("module", models.CharField(default="POS", max_length=30)),
                ("group", models.CharField(default="Geral", max_length=40)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="pos.posright",
                    ),
                ),
            ],
            options={
                "db_table": "pos_right",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="PosUserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("memo", models.TextField(blank=True, null=True)),
                (
                    "default_module",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("pos_tables", models.JSONField(blank=True, default=dict)),
                ("pos_documents", models.JSONField(blank=True, default=dict)),
                ("pos_shortcuts", models.JSONField(blank=True, default=dict)),
                ("pos_payments", models.JSONField(blank=True, default=dict)),
                ("data_protection", models.JSONField(blank=True, default=dict)),
                (
                    "rights",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="pos.posright"
                    ),
                ),
            ],
            options={
                "db_table": "pos_user_group",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PosScheduleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda"),
                            (1, "Terça"),
                            (2, "Quarta"),
                            (3, "Quinta"),
                            (4, "Sexta"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                (
                    "band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_lines",
                        to="pos.timeband",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pos.posschedule",
                    ),
                ),
            ],
            options={
                "db_table": "pos_schedule_line",
                "ordering": ["weekday"],
                "unique_together": {("schedule", "weekday", "band")},
            },
        ),
    ]
