# Generated by Django 6.0.4 on 2026-07-12 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_reportdefinition"),
        ("pos", "0025_posschedule_posright_posusergroup_posscheduleline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PosUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("must_change_password", models.BooleanField(default=False)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=60, null=True)),
                ("first_name", models.CharField(blank=True, max_length=60, null=True)),
                ("language", models.CharField(default="pt-PT", max_length=10)),
                ("section", models.CharField(blank=True, max_length=60, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("direct_dial", models.CharField(blank=True, max_length=40, null=True)),
                ("position", models.CharField(blank=True, max_length=60, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("entry_date", models.DateField(blank=True, null=True)),
                ("exit_date", models.DateField(blank=True, null=True)),
                ("cash_registers", models.JSONField(blank=True, default=dict)),
                (
                    "imp_data_access",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "imp_reporting",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "imp_sql_server",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "imp_database",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("all_complexes", models.BooleanField(default=True)),
                ("complexes", models.JSONField(blank=True, default=list)),
                ("rate_sections", models.JSONField(blank=True, default=list)),
                ("street", models.CharField(blank=True, max_length=150, null=True)),
                ("city", models.CharField(blank=True, max_length=60, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(default="Angola", max_length=60)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                ("mobile", models.CharField(blank=True, max_length=40, null=True)),
                ("fax", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "personal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("all_sectors", models.BooleanField(default=True)),
                ("internal_consumption", models.BooleanField(default=False)),
                (
                    "discount_profile",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("use_cost_price", models.BooleanField(default=False)),
                ("pos_pin", models.CharField(blank=True, max_length=128, null=True)),
                ("pos_must_change_pin", models.BooleanField(default=False)),
                ("is_event_manager", models.BooleanField(default=False)),
                ("email_group", models.CharField(blank=True, max_length=60, null=True)),
                ("is_fnb_user", models.BooleanField(default=False)),
                ("memo", models.TextField(blank=True, null=True)),
                ("email_signature", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "auth_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="pos.posusergroup",
                    ),
                ),
                (
                    "pos_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_users",
                        to="pos.posusergroup",
                    ),
                ),
                (
                    "sectors",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="pos.possector"
                    ),
                ),
            ],
            options={
                "db_table": "pos_user",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PosUserCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[("PERCENT", "Percentagem"), ("VALUE", "Valor fixo")],
                        default="PERCENT",
                        max_length=8,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="inventory.item",
                    ),
                ),
                (
                    "subfamily",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="inventory.itemsubfamily",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="pos.posuser",
                    ),
                ),
            ],
            options={
                "db_table": "pos_user_commission",
            },
        ),
    ]
