# Generated by Django 6.0.4 on 2026-07-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_reportdefinition"),
        ("pos", "0026_posuser_posusercommission"),
    ]

    operations = [
        migrations.CreateModel(
            name="HRType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pos_hr_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="HumanResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Feminino"), ("M", "Masculino"), ("O", "Outro")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "license_code",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_front_office_user", models.BooleanField(default=False)),
                ("schedule_from", models.DateField(blank=True, null=True)),
                ("schedule_to", models.DateField(blank=True, null=True)),
                (
                    "hr_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="pos.hrtype",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True, related_name="resources", to="inventory.item"
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="pos.possector",
                    ),
                ),
            ],
            options={
                "db_table": "pos_human_resource",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="HRScheduleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("time_from", models.TimeField()),
                ("time_to", models.TimeField()),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="pos.humanresource",
                    ),
                ),
            ],
            options={
                "db_table": "pos_hr_schedule",
                "ordering": ["weekday", "time_from"],
            },
        ),
        migrations.CreateModel(
            name="HRCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[("PERCENT", "Percentagem"), ("VALUE", "Valor fixo")],
                        default="PERCENT",
                        max_length=8,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_commissions",
                        to="inventory.item",
                    ),
                ),
                (
                    "subfamily",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_commissions",
                        to="inventory.itemsubfamily",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="pos.humanresource",
                    ),
                ),
            ],
            options={
                "db_table": "pos_hr_commission",
            },
        ),
    ]
