# Generated by Django 6.0.4 on 2026-07-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_reportdefinition"),
        ("pos", "0027_hrtype_humanresource_hrscheduleline_hrcommission"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "base",
                    models.CharField(
                        choices=[("PERCENT", "Percentagem"), ("VALUE", "Valor")],
                        default="PERCENT",
                        max_length=8,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("for_pms", models.BooleanField(default=False)),
                ("for_ems", models.BooleanField(default=False)),
                ("for_pos", models.BooleanField(default=True)),
                ("allow_manual", models.BooleanField(default=False)),
                (
                    "calc_mode",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Geral"),
                            ("NIGHTS", "Por noites"),
                            ("FIRST", "Primeira noite"),
                        ],
                        default="GENERAL",
                        max_length=10,
                    ),
                ),
                ("calc_base", models.CharField(blank=True, max_length=20, null=True)),
                ("set_nights", models.BooleanField(default=False)),
                ("stay_nights", models.PositiveIntegerField(default=0)),
                ("paid_nights", models.PositiveIntegerField(default=0)),
                ("use_intervals", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, related_name="pos_discounts", to="inventory.item"
                    ),
                ),
                (
                    "user_groups",
                    models.ManyToManyField(
                        blank=True, related_name="discounts", to="pos.posusergroup"
                    ),
                ),
            ],
            options={
                "db_table": "pos_discount",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="posticket",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="pos.posdiscount",
            ),
        ),
    ]
