# Generated by Django 6.0.4 on 2026-07-12 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0028_posdiscount_posticket_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="PmsHotelLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("hotel_id", models.CharField(default="0", max_length=20)),
                ("description", models.CharField(max_length=120)),
                ("server", models.CharField(blank=True, max_length=120, null=True)),
                ("database", models.CharField(blank=True, max_length=120, null=True)),
                ("trusted", models.BooleanField(default=False)),
                ("username", models.CharField(blank=True, max_length=60, null=True)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                ("charge_code", models.CharField(blank=True, max_length=40, null=True)),
                ("paymaster", models.CharField(blank=True, max_length=20, null=True)),
                ("taxes", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("SIMPLE", "Simples"), ("FULL", "Completo")],
                        default="SIMPLE",
                        max_length=8,
                    ),
                ),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_ok", models.BooleanField(default=False)),
                (
                    "last_test_detail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "pos_pms_hotel_link",
                "ordering": ["description"],
            },
        ),
        migrations.AddField(
            model_name="possector",
            name="pms_default_account",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="possector",
            name="pms_department",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="possector",
            name="pms_paymaster",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="possector",
            name="pms_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="PmsExternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("company_id", models.CharField(default="0", max_length=20)),
                ("server", models.CharField(blank=True, max_length=120, null=True)),
                ("database", models.CharField(blank=True, max_length=120, null=True)),
                ("trusted", models.BooleanField(default=False)),
                ("username", models.CharField(blank=True, max_length=60, null=True)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_ok", models.BooleanField(default=False)),
                (
                    "last_test_detail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sector",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_link",
                        to="pos.possector",
                    ),
                ),
            ],
            options={
                "db_table": "pos_pms_external_link",
            },
        ),
    ]
