# Generated by Django 6.0.4 on 2026-07-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0011_alter_unitofmeasure_options_unitofmeasure_is_active_and_more",
        ),
        ("pos", "0029_pmshotellink_possector_pms_default_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoidReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("key_label", models.CharField(max_length=80)),
                ("print_label", models.CharField(max_length=80)),
                ("sort_order", models.PositiveIntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pos_void_reason",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="HappyHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("PRICE", "Preço"), ("DISCOUNT", "Desconto")],
                        default="PRICE",
                        max_length=8,
                    ),
                ),
                ("show_half_hours", models.BooleanField(default=False)),
                ("cells", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="happy_hours",
                        to="pos.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "pos_happy_hour",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockErpLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("name", models.CharField(default="ERP Externo", max_length=60)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                ("instance", models.CharField(blank=True, max_length=60, null=True)),
                ("company", models.CharField(blank=True, max_length=60, null=True)),
                ("username", models.CharField(blank=True, max_length=60, null=True)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                ("stock_control", models.BooleanField(default=False)),
                (
                    "block_mode",
                    models.CharField(
                        choices=[
                            ("WARN", "Avisar"),
                            ("BLOCK", "Bloqueio"),
                            ("NONE", "Não controlar"),
                        ],
                        default="WARN",
                        max_length=6,
                    ),
                ),
                ("import_rows", models.PositiveIntegerField(default=500)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_ok", models.BooleanField(default=False)),
                (
                    "last_test_detail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.itemfamily",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.itemgroup",
                    ),
                ),
                (
                    "subfamily",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.itemsubfamily",
                    ),
                ),
            ],
            options={
                "db_table": "pos_stock_erp_link",
            },
        ),
    ]
