# Generated by Django 6.0.4 on 2026-07-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0030_voidreason_happyhour_stockerplink"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosHardware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hw_type",
                    models.CharField(
                        choices=[
                            ("PRINTER", "Impressora"),
                            ("DRAWER", "Gaveta"),
                            ("SCALE", "Balança"),
                            ("SCANNER", "Leitor de códigos"),
                            ("DISPLAY", "Display de cliente"),
                            ("CARD", "Terminal bancário (TPA)"),
                            ("KDS", "Monitor de cozinha"),
                            ("OTHER", "Outro"),
                        ],
                        default="PRINTER",
                        max_length=10,
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("port", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "baud_rate",
                    models.PositiveIntegerField(
                        choices=[
                            (2400, "2400"),
                            (4800, "4800"),
                            (9600, "9600"),
                            (19200, "19200"),
                            (38400, "38400"),
                            (57600, "57600"),
                            (115200, "115200"),
                        ],
                        default=9600,
                    ),
                ),
                (
                    "flow_control",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("XONXOFF", "XON/XOFF"),
                            ("RTSCTS", "RTS/CTS"),
                        ],
                        default="NONE",
                        max_length=8,
                    ),
                ),
                (
                    "parity",
                    models.CharField(
                        choices=[("NONE", "None"), ("EVEN", "Even"), ("ODD", "Odd")],
                        default="NONE",
                        max_length=6,
                    ),
                ),
                ("stop_bits", models.PositiveSmallIntegerField(default=1)),
                ("data_bits", models.PositiveSmallIntegerField(default=8)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pos_hardware",
                "ordering": ["hw_type", "code"],
            },
        ),
    ]
