# Generated by Django 6.0.4 on 2026-07-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0031_poshardware"),
    ]

    operations = [
        migrations.AddField(
            model_name="printjob",
            name="error",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
