# Generated by Django 6.0.4 on 2026-07-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_printer_device_printer_warn_on_failure"),
        ("pos", "0032_printjob_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="KdsMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[("ORDER", "Por pedido"), ("ITEM", "Por artigo")],
                        default="ORDER",
                        max_length=6,
                    ),
                ),
                (
                    "station",
                    models.CharField(
                        choices=[
                            ("KITCHEN", "Cozinha"),
                            ("BAR", "Bar"),
                            ("PASTRY", "Pastelaria"),
                            ("CASHIER", "Caixa"),
                        ],
                        default="KITCHEN",
                        max_length=10,
                    ),
                ),
                ("buttons", models.JSONField(blank=True, default=list)),
                ("options", models.JSONField(blank=True, default=dict)),
                (
                    "header_text",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "header_image_url",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "footer_notifications",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "printers",
                    models.ManyToManyField(
                        blank=True, related_name="kds_monitors", to="inventory.printer"
                    ),
                ),
            ],
            options={
                "db_table": "pos_kds_monitor",
                "ordering": ["code"],
            },
        ),
    ]
