# Generated by Django 6.0.4 on 2026-07-12 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0033_kdsmonitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("for_ems", models.BooleanField(default=False)),
                ("for_pos", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pos_customer_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("ENTITY", "Entidade"),
                            ("RESERVATION", "Reserva (Detalhe)"),
                            ("TICKET", "Conta POS"),
                            ("ITEM", "Artigo"),
                            ("GUEST", "Hóspede"),
                        ],
                        default="RESERVATION",
                        max_length=12,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Texto"),
                            ("NUMBER", "Número"),
                            ("DATE", "Data"),
                            ("BOOL", "Sim/Não"),
                            ("LIST", "Lista"),
                        ],
                        default="TEXT",
                        max_length=8,
                    ),
                ),
                ("read_permission", models.PositiveIntegerField(default=0)),
                ("write_permission", models.PositiveIntegerField(default=0)),
                ("regex", models.CharField(blank=True, max_length=200, null=True)),
                ("size", models.PositiveIntegerField(default=0)),
                ("lines", models.PositiveIntegerField(default=0)),
                ("is_list", models.BooleanField(default=False)),
                ("list_values", models.JSONField(blank=True, default=list)),
                (
                    "default_value",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("show_in_search", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pos_custom_field",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SmartCash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("CASHLOGY", "Cashlogy"),
                            ("CASHDRO", "CashDro"),
                            ("GLORY", "Glory"),
                            ("OTHER", "Outro"),
                        ],
                        default="CASHLOGY",
                        max_length=10,
                    ),
                ),
                (
                    "url_operations",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("url_menu", models.CharField(blank=True, max_length=250, null=True)),
                ("username", models.CharField(blank=True, max_length=60, null=True)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_ok", models.BooleanField(default=False)),
                (
                    "last_test_detail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smart_cash",
                        to="pos.posterminal",
                    ),
                ),
            ],
            options={
                "db_table": "pos_smart_cash",
                "ordering": ["code"],
            },
        ),
    ]
