# Generated by Django 6.0.4 on 2026-07-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0034_customertype_customfielddef_smartcash"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "card_kind",
                    models.CharField(
                        choices=[
                            ("MAGNETIC", "Banda magnética"),
                            ("RFID", "RFID / Contactless"),
                            ("BARCODE", "Código de barras"),
                            ("QR", "QR Code"),
                            ("MANUAL", "Manual"),
                        ],
                        default="MAGNETIC",
                        max_length=10,
                    ),
                ),
                ("length", models.PositiveSmallIntegerField(default=0)),
                (
                    "start_sentinel",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("end_sentinel", models.CharField(blank=True, max_length=4, null=True)),
                ("pos_start", models.PositiveSmallIntegerField(default=0)),
                ("pos_end", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pos_card_type",
                "ordering": ["code"],
            },
        ),
    ]
