# Generated by Django 6.0.4 on 2026-07-12 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_printer_device_printer_warn_on_failure"),
        ("pos", "0035_cardtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.CharField(blank=True, max_length=200, null=True)),
                ("has_credit", models.BooleanField(default=False)),
                ("has_debit", models.BooleanField(default=False)),
                ("has_points", models.BooleanField(default=False)),
                ("has_discount", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "happy_hour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_cards",
                        to="pos.happyhour",
                    ),
                ),
                (
                    "packages",
                    models.ManyToManyField(
                        blank=True, related_name="member_cards", to="inventory.item"
                    ),
                ),
            ],
            options={
                "db_table": "pos_member_card",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="MemberCardDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="pos.membercard",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_discounts",
                        to="inventory.item",
                    ),
                ),
                (
                    "subfamily",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_discounts",
                        to="inventory.itemsubfamily",
                    ),
                ),
            ],
            options={
                "db_table": "pos_member_card_discount",
            },
        ),
    ]
