# Generated by Django 6.0.4 on 2026-07-12 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0036_membercard_membercarddiscount"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectionCodeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=140)),
                ("translations", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "mkt_selcode_group",
                "ordering": ["number", "code"],
            },
        ),
        migrations.CreateModel(
            name="TemplateAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("culture", models.CharField(default="pt-PT", max_length=10)),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("Events", "Eventos"),
                            ("Reservations", "Reservas"),
                            ("Invoices", "Faturas"),
                            ("Pos", "POS"),
                        ],
                        default="Events",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("file_url", models.CharField(blank=True, max_length=300, null=True)),
                ("file_name", models.CharField(blank=True, max_length=200, null=True)),
                ("is_report", models.BooleanField(default=False)),
                (
                    "report_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("detailed", models.BooleanField(default=False)),
                (
                    "report_criteria",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mkt_attachment",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_sms", models.BooleanField(default=False)),
                ("sender", models.CharField(blank=True, max_length=200, null=True)),
                ("send_to", models.CharField(blank=True, max_length=200, null=True)),
                ("cc", models.CharField(blank=True, max_length=200, null=True)),
                ("bcc", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "reservation_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("NORMAL", "Normal"),
                            ("PENDING", "Pendente"),
                            ("CONFIRMED", "Confirmada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=60, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("booking_priority", models.BooleanField(default=False)),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("Reservations", "Reservas"),
                            ("Invoices", "Faturas"),
                            ("FixedCharges", "Encargos"),
                            ("HotelInfo", "Dados do Hotel"),
                            ("EMenuOrders", "Pedidos e-Menu"),
                            ("Events", "Eventos"),
                            ("PosTickets", "Contas POS"),
                        ],
                        default="Reservations",
                        max_length=20,
                    ),
                ),
                ("is_sub_template", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sms_pair",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_of",
                        to="pos.emailtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "mkt_email_template",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="TemplateVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("Reservations", "Reservas"),
                            ("Events", "Eventos"),
                            ("Invoices", "Faturas"),
                            ("Pos", "POS"),
                        ],
                        default="Reservations",
                        max_length=20,
                    ),
                ),
                ("culture", models.CharField(default="pt-PT", max_length=10)),
                ("field", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=140)),
                ("group", models.CharField(blank=True, max_length=60, null=True)),
                ("group_name", models.CharField(blank=True, max_length=100, null=True)),
                ("subgroup", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "subgroup_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("query", models.TextField(blank=True, null=True)),
                ("date_format", models.CharField(blank=True, max_length=40, null=True)),
                ("is_table", models.BooleanField(default=False)),
                (
                    "table_style",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "header_style",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "text_before",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("text_style", models.CharField(blank=True, max_length=200, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mkt_variable",
                "ordering": ["group", "subgroup", "name"],
                "unique_together": {("context", "culture", "field")},
            },
        ),
        migrations.CreateModel(
            name="EmailTemplateText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("culture", models.CharField(max_length=10)),
                ("subject", models.CharField(blank=True, max_length=300, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to="pos.emailtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "mkt_email_text",
                "unique_together": {("template", "culture")},
            },
        ),
        migrations.CreateModel(
            name="SelectionCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=140)),
                ("translations", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="pos.selectioncodegroup",
                    ),
                ),
            ],
            options={
                "db_table": "mkt_selcode",
                "ordering": ["group", "number", "code"],
                "unique_together": {("group", "code")},
            },
        ),
    ]
