# Generated by Django 6.0.4 on 2026-07-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0037_selectioncodegroup_templateattachment_emailtemplate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAdditionalState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("for_pms", models.BooleanField(default=True)),
                ("for_ems", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ev_additional_state",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EventReservationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=60)),
                (
                    "equivalent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Nenhum"),
                            ("NORMAL", "Normal"),
                            ("OPTION", "Opção"),
                            ("WAITLIST", "Lista de Espera"),
                            ("PENDING", "Pendente"),
                            ("CANCELLED", "Cancelamento"),
                            ("NOSHOW", "No-show"),
                            ("CHECKIN", "Check-in"),
                            ("CHECKOUT", "Check-out"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("text_key", models.CharField(blank=True, max_length=40, null=True)),
                ("bg_color", models.CharField(default="#ffffff", max_length=20)),
                ("text_color", models.CharField(default="#333333", max_length=20)),
                ("is_system", models.BooleanField(default=False)),
                ("is_auto_reservation", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ev_reservation_state",
                "ordering": ["sort_order", "code"],
            },
        ),
    ]
