# Generated by Django 6.0.4 on 2026-07-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_printer_device_printer_warn_on_failure"),
        ("pos", "0038_eventadditionalstate_eventreservationstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributionChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("for_pms", models.BooleanField(default=True)),
                ("for_ems", models.BooleanField(default=True)),
                ("for_pos", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ev_channel",
                "ordering": ["number", "code"],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("for_pms", models.BooleanField(default=True)),
                ("for_ems", models.BooleanField(default=True)),
                ("for_pos", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ev_segment",
                "ordering": ["number", "code"],
            },
        ),
        migrations.CreateModel(
            name="SpaceLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "name_lang_1",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "name_lang_2",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "name_lang_3",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ev_space_layout",
                "ordering": ["number", "code"],
            },
        ),
        migrations.CreateModel(
            name="SpaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                ("for_ems", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ev_space_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EventCancelReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("for_pms", models.BooleanField(default=True)),
                ("for_ems", models.BooleanField(default=True)),
                ("default_auto_cancel", models.BooleanField(default=False)),
                ("default_abandon", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "charge_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancel_reasons",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "ev_cancel_reason",
                "ordering": ["number", "code"],
            },
        ),
        migrations.CreateModel(
            name="EventPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "name_lang_1",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "name_lang_2",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "name_lang_3",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="pos.possector",
                    ),
                ),
            ],
            options={
                "db_table": "ev_package",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EventPackageLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pos.eventpackage",
                    ),
                ),
            ],
            options={
                "db_table": "ev_package_line",
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_event_type", models.BooleanField(default=True)),
                ("is_service_type", models.BooleanField(default=True)),
                ("default_start", models.TimeField(blank=True, null=True)),
                ("default_end", models.TimeField(blank=True, null=True)),
                (
                    "name_lang_1",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "name_lang_2",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "name_lang_3",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("for_ems", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_types",
                        to="pos.posuser",
                    ),
                ),
            ],
            options={
                "db_table": "ev_event_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PlanningOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("bg_color", models.CharField(default="#ffffff", max_length=20)),
                ("text_color", models.CharField(default="#333333", max_length=20)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_options",
                        to="pos.possector",
                    ),
                ),
            ],
            options={
                "db_table": "ev_planning_option",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SubSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("for_pms", models.BooleanField(default=True)),
                ("for_ems", models.BooleanField(default=True)),
                ("for_pos", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subsegments",
                        to="pos.segment",
                    ),
                ),
            ],
            options={
                "db_table": "ev_subsegment",
                "ordering": ["number", "code"],
            },
        ),
    ]
