# Generated by Django 6.0.4 on 2026-07-13 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0039_distributionchannel_segment_spacelayout_spacetype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "fnb_cost_center",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("days", models.PositiveIntegerField(default=0)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "fnb_payment_term",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="StockDocStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("equivalent", models.CharField(blank=True, max_length=20, null=True)),
                ("text_key", models.CharField(blank=True, max_length=40, null=True)),
                ("bg_color", models.CharField(default="#ffffff", max_length=20)),
                ("text_color", models.CharField(default="#333333", max_length=20)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_system", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "fnb_doc_status",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="StockDocSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("STOCK", "Stocks"),
                            ("SALES_STOCK", "Stock de Vendas"),
                            ("REQUEST", "Requisição"),
                            ("TRANSFER", "Transferência"),
                            ("INVENTORY", "Inventário"),
                            ("ORDER", "Encomenda"),
                            ("INVOICE", "Faturação"),
                            ("DELIVERY", "Guia"),
                        ],
                        default="STOCK",
                        max_length=12,
                    ),
                ),
                ("series_number", models.CharField(default="1", max_length=20)),
                ("year", models.PositiveIntegerField(default=0)),
                ("current_number", models.PositiveIntegerField(default=0)),
                ("last_doc_date", models.DateField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("links_stock", models.BooleanField(default=True)),
                ("links_current_account", models.BooleanField(default=False)),
                ("convertible", models.BooleanField(default=False)),
                ("allow_future", models.BooleanField(default=False)),
                ("notes_required", models.BooleanField(default=False)),
                (
                    "nature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RECEIVABLE", "Documento a receber"),
                            ("PAYABLE", "Documento a pagar"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "external_dup",
                    models.CharField(
                        choices=[
                            ("IGNORE", "Ignorar duplicação"),
                            ("WARN", "Informar sobre duplicação"),
                            ("BLOCK", "Não permite duplicação"),
                        ],
                        default="IGNORE",
                        max_length=8,
                    ),
                ),
                ("external_required", models.BooleanField(default=False)),
                ("updates_avg_cost", models.BooleanField(default=True)),
                ("updates_last_price", models.BooleanField(default=True)),
                ("updates_last_entry_date", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "statuses",
                    models.ManyToManyField(
                        blank=True, related_name="doc_series", to="pos.stockdocstatus"
                    ),
                ),
            ],
            options={
                "db_table": "fnb_doc_series",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="StockPrintModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(default="Normal", max_length=40)),
                ("code", models.CharField(default="1", max_length=20)),
                (
                    "description",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("model_path", models.CharField(blank=True, max_length=250, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_models",
                        to="pos.stockdocseries",
                    ),
                ),
            ],
            options={
                "db_table": "fnb_print_model",
                "ordering": ["sort_order"],
            },
        ),
    ]
