# Generated by Django 6.0.4 on 2026-07-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0040_costcenter_paymentterm_stockdocstatus_stockdocseries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posauditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("TICKET_OPEN", "Ticket aberto"),
                    ("LINE_ADD", "Linha adicionada"),
                    ("LINE_VOID", "Linha removida"),
                    ("KITCHEN_FIRE", "Enviado p/ cozinha"),
                    ("KDS_ADVANCE", "Estado de produção"),
                    ("PAYMENT", "Pagamento"),
                    ("DOC_ISSUE", "Documento emitido"),
                    ("DOC_VOID", "Documento anulado"),
                    ("TICKET_VOID", "Ticket anulado"),
                    ("TABLE_CHANGE", "Transferência de mesa"),
                    ("CASH_OPEN", "Abertura de caixa"),
                    ("CASH_MOVE", "Movimento de caixa"),
                    ("CASH_CLOSE", "Fecho de caixa"),
                ],
                max_length=20,
            ),
        ),
    ]
