# Generated by Django 6.0.4 on 2026-07-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0042_eventrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityFieldRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("name", "Nome"),
                            ("last_name", "Apelido"),
                            ("other_names", "Outros nomes"),
                            ("tax_id", "Nr. contribuinte"),
                            ("id_number", "Nr. de identificação"),
                            ("email", "E-mail"),
                            ("phone", "Telefone"),
                            ("address", "Morada"),
                            ("country", "País"),
                            ("nationality", "Nacionalidade"),
                            ("birth_date", "Data de nascimento"),
                            ("entity_type", "Tipo de entidade"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "mkt_entity_field_rule",
                "ordering": ["field"],
            },
        ),
        migrations.AddField(
            model_name="eventrequest",
            name="answered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventrequest",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventrequest",
            name="answered_by",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
