# Generated by Django 6.0.4 on 2026-07-13 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0013_fiscalseries_at_processing_mean_and_more"),
        ("mdm", "0012_customer_member_card_customer_member_card_number"),
        ("pos", "0043_entityfieldrule_eventrequest_answered_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("IN", "Entrada (depósito)"),
                            ("USE", "Utilização"),
                            ("OUT", "Devolução"),
                        ],
                        default="IN",
                        max_length=4,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reason", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "cash_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deposits",
                        to="pos.cashsession",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits",
                        to="mdm.customer",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deposit_uses",
                        to="fiscal.fiscaldocument",
                    ),
                ),
            ],
            options={
                "db_table": "pos_entity_deposit",
                "ordering": ["-created_at"],
            },
        ),
    ]
