# Generated by Django 6.0.4 on 2026-07-13 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_warehouse_accounting_account_warehouse_address1_and_more"),
        ("mdm", "0012_customer_member_card_customer_member_card_number"),
        ("pos", "0044_entitydeposit"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=30)),
                ("doc_date", models.DateField()),
                (
                    "external_ref",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("tax_included", models.BooleanField(default=False)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("voided", models.BooleanField(default=False)),
                ("paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_docs",
                        to="pos.costcenter",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_docs",
                        to="mdm.customer",
                    ),
                ),
                (
                    "original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to="pos.stockdoc",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_docs",
                        to="pos.paymentterm",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="pos.stockdocseries",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="pos.stockdocstatus",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_docs",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "warehouse_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_docs_out",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "fnb_stock_doc",
                "ordering": ["-doc_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockDocLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                ("lot", models.CharField(blank=True, max_length=40, null=True)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pos.stockdoc",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_doc_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doc_lines",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "fnb_stock_doc_line",
            },
        ),
    ]
