# Generated by Django 6.0.4 on 2026-07-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0045_stockdoc_stockdocline"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdocline",
            name="theoretical_cost",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stockdocline",
            name="theoretical_qty",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
