# Generated by Django 6.0.4 on 2026-07-13 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0012_customer_member_card_customer_member_card_number"),
        ("pos", "0046_stockdocline_theoretical_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercard",
            name="credit_limit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="membercard",
            name="point_value",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name="membercard",
            name="points_per_100",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.CreateModel(
            name="MemberCardMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LOAD", "Carregamento (crédito)"),
                            ("SPEND", "Consumo do crédito"),
                            ("DEBIT", "Dívida (débito)"),
                            ("SETTLE", "Liquidação da dívida"),
                            ("EARN", "Pontos ganhos"),
                            ("REDEEM", "Pontos usados"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reason", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="pos.membercard",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_movements",
                        to="mdm.customer",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_movements",
                        to="pos.posticket",
                    ),
                ),
            ],
            options={
                "db_table": "pos_member_card_movement",
                "ordering": ["-created_at"],
            },
        ),
    ]
