# Generated by Django 6.0.4 on 2026-07-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0047_membercard_credit_limit_membercard_point_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posterminal",
            name="keyboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terminals",
                to="pos.poskeyboard",
            ),
        ),
    ]
