# Generated by Django 6.0.4 on 2026-07-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0048_posterminal_keyboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="posticket",
            name="guest_type",
            field=models.CharField(
                choices=[
                    ("PASSANTE", "Passante"),
                    ("HOTEL", "Hotel"),
                    ("INTERNO", "Consumo Interno"),
                ],
                default="PASSANTE",
                max_length=10,
            ),
        ),
    ]
