# Generated by Django 6.0.4 on 2026-07-16 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0049_posticket_guest_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to", models.CharField(max_length=500)),
                ("subject", models.CharField(max_length=300)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "context_ref",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Em fila"),
                            ("SENT", "Enviado"),
                            ("SIMULATED", "Simulado (sem SMTP)"),
                            ("FAILED", "Falhou"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to="pos.emailtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "mkt_email_outbox",
                "ordering": ["-created_at"],
            },
        ),
    ]
