# Generated by Django 6.0.4 on 2026-07-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0050_emailoutbox"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderline",
            name="order",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderline",
            name="item",
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="table",
            name="area",
        ),
        migrations.RemoveField(
            model_name="table",
            name="hotel",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="OrderLine",
        ),
        migrations.DeleteModel(
            name="Table",
        ),
    ]
