# Generated by Django 6.0.4 on 2026-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0051_remove_orderline_order_remove_payment_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posticketline",
            name="served_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
