# Generated by Django 6.0.4 on 2026-07-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_warehouse_accounting_account_warehouse_address1_and_more"),
        ("pos", "0052_posticketline_served_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("photo_url", models.CharField(blank=True, max_length=400, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pos_allergen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KitchenMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_message", models.BooleanField(default=True)),
                ("is_comment", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Mensagem para a cozinha",
                "verbose_name_plural": "Mensagens para a cozinha",
                "db_table": "pos_kitchen_message",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ItemPosProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prep_notes", models.TextField(blank=True, null=True)),
                (
                    "allergens",
                    models.ManyToManyField(
                        blank=True, related_name="items", to="pos.allergen"
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_profile",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "pos_item_profile",
            },
        ),
        migrations.CreateModel(
            name="KitchenMessageOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("text", models.CharField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="pos.kitchenmessage",
                    ),
                ),
            ],
            options={
                "db_table": "pos_kitchen_message_option",
                "ordering": ["sort_order", "code"],
            },
        ),
    ]
