# Generated by Django 6.0.4 on 2026-07-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0054_dados_para_o_pos"),
    ]

    operations = [
        migrations.AddField(
            model_name="posticketline",
            name="discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
