# Generated by Django 6.0.4 on 2026-07-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_warehouse_accounting_account_warehouse_address1_and_more"),
        ("pos", "0055_posticketline_discount_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchenmessage",
            name="ask_on_add",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenmessage",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="kitchen_messages", to="inventory.item"
            ),
        ),
    ]
