# Generated by Django 6.0.4 on 2026-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0056_kitchenmessage_ask_on_add_kitchenmessage_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="posticket",
            name="payment_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
