# Generated by Django 6.0.4 on 2026-07-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0057_posticket_payment_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="poskeyboardkey",
            name="cols",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poskeyboardkey",
            name="price_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poskeyboardkey",
            name="rows",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
