# Generated by Django 6.0.4 on 2026-07-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0058_poskeyboardkey_cols_poskeyboardkey_price_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posticketpayment",
            name="auth_code",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="posticketpayment",
            name="bank_reference",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="posticketpayment",
            name="document_number",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="posticketpayment",
            name="room_ref",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
