# Generated by Django 6.0.4 on 2026-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0059_posticketpayment_auth_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashmovement",
            name="internal_consumption",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cashmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("SANGRIA", "Sangria"),
                    ("REFORCO", "Reforço"),
                    ("ENTRADA", "Entrada Manual"),
                    ("SAIDA", "Saída Manual"),
                    ("GRATIFICACAO", "Gratificação"),
                ],
                max_length=13,
            ),
        ),
    ]
