# Generated by Django 6.0.4 on 2026-07-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0060_cashmovement_internal_consumption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posticketline",
            name="is_gift",
            field=models.BooleanField(default=False),
        ),
    ]
