# Generated by Django 6.0.4 on 2026-07-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0061_posticketline_is_gift"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdoc",
            name="analytic_account",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
