# Generated by Django 6.0.4 on 2026-07-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0062_stockdoc_analytic_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="printjob",
            name="opens_drawer",
            field=models.BooleanField(default=True),
        ),
    ]
