# Generated by Django 6.0.4 on 2026-07-29 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0063_printjob_opens_drawer"),
    ]

    operations = [
        migrations.AddField(
            model_name="posuser",
            name="keyboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="pos.poskeyboard",
            ),
        ),
    ]
