# Generated by Django 6.0.4 on 2026-10-01 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0064_posuser_keyboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="ID da ficha")),
                ("value", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="pos.customfielddef",
                    ),
                ),
            ],
            options={
                "db_table": "pos_custom_field_value",
                "indexes": [
                    models.Index(
                        fields=["field", "object_id"],
                        name="pos_custom__field_i_926b80_idx",
                    )
                ],
                "unique_together": {("field", "object_id")},
            },
        ),
    ]
