# Generated by Django 6.0.4 on 2026-07-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "support_url",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "support_token",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("auto_send_logs", models.BooleanField(default=False)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("remote_assist_enabled", models.BooleanField(default=False)),
                ("remote_assist_until", models.DateTimeField(blank=True, null=True)),
                (
                    "remote_assist_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "db_table": "licensing_support_setting",
            },
        ),
    ]
