# Generated by Django 6.0.4 on 2026-07-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0002_supportsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportsetting",
            name="latest_download_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="supportsetting",
            name="latest_release_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportsetting",
            name="latest_version",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="supportsetting",
            name="version_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
