# Generated by Django 6.0.7 on 2026-07-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Pessoa Singular"),
                            ("COMPANY", "Empresa"),
                            ("GROUP", "Grupo Empresarial"),
                        ],
                        default="COMPANY",
                        max_length=20,
                    ),
                ),
                ("commercial_name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nif",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("vat_number", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("currency", models.CharField(default="AOA", max_length=10)),
                ("language", models.CharField(default="pt-PT", max_length=20)),
                ("country", models.CharField(default="Angola", max_length=100)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("zone", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "minimum_order_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("delivery_days", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("BLOCKED", "Bloqueado"),
                            ("EVALUATION", "Em Avaliação"),
                        ],
                        default="EVALUATION",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="suppliers", to="esm.suppliercategory"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PURCHASING", "Compras"),
                            ("FINANCE", "Financeiro"),
                            ("LOGISTICS", "Logística"),
                            ("COMMERCIAL", "Comercial"),
                            ("EMERGENCY", "Emergência"),
                            ("SUPPORT", "Suporte"),
                        ],
                        default="COMMERCIAL",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="esm.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "base_discount_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("bonus_description", models.TextField(blank=True, null=True)),
                ("incoterms", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="esm.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "Contrato"),
                            ("LICENSE", "Licença"),
                            ("CERTIFICATE", "Certificado (ISO, HACCP)"),
                            ("INSURANCE", "Seguro"),
                            ("PERMIT", "Alvará"),
                            ("OTHER", "Outro"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_url", models.URLField(blank=True, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="esm.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierPerformanceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.IntegerField(default=100)),
                (
                    "punctuality_percentage",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "completeness_percentage",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "price_variance_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "return_rate_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("total_orders", models.IntegerField(default=0)),
                ("total_grns", models.IntegerField(default=0)),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_profile",
                        to="esm.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierQualityControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requires_haccp", models.BooleanField(default=False)),
                ("requires_cold_chain", models.BooleanField(default=False)),
                (
                    "required_temperature",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("audit_notes", models.TextField(blank=True, null=True)),
                ("last_audit_date", models.DateField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_controls",
                        to="esm.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierProductCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_item_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("agreed_price", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "vat_percentage",
                    models.DecimalField(decimal_places=2, default=14.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="supplier_catalogs",
                        to="inventory.item",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog",
                        to="esm.supplier",
                    ),
                ),
            ],
            options={
                "unique_together": {("supplier", "item")},
            },
        ),
    ]
