# Generated by Django 6.0.4 on 2026-07-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FiscalAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=40)),
                (
                    "document_ref",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("user", models.CharField(blank=True, max_length=100, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fis_audit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FiscalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_nif", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("tax_regime", models.CharField(default="Regime Geral", max_length=60)),
                (
                    "vat_regime",
                    models.CharField(default="Regime Geral do IVA", max_length=60),
                ),
                ("tax_office", models.CharField(blank=True, max_length=100, null=True)),
                ("certificate_number", models.CharField(default="0000", max_length=20)),
                ("key_version", models.PositiveIntegerField(default=1)),
                (
                    "environment",
                    models.CharField(
                        choices=[("TEST", "Testes"), ("PROD", "Produção")],
                        default="TEST",
                        max_length=4,
                    ),
                ),
                ("qr_enabled", models.BooleanField(default=True)),
                ("saft_version", models.CharField(default="1.01_01", max_length=20)),
                (
                    "generic_customer_nif",
                    models.CharField(default="999999999", max_length=20),
                ),
            ],
            options={
                "db_table": "fis_config",
            },
        ),
        migrations.CreateModel(
            name="FiscalDocType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "saft_type",
                    models.CharField(
                        choices=[
                            ("SalesInvoice", "Documento comercial (4.1)"),
                            ("WorkingDocument", "Documento de conferência (4.3)"),
                            ("MovementOfGoods", "Movimentação de mercadorias (4.2)"),
                            ("Payment", "Recibo (4.4)"),
                        ],
                        default="SalesInvoice",
                        max_length=20,
                    ),
                ),
                ("invoice_type", models.CharField(blank=True, max_length=6, null=True)),
                ("signable", models.BooleanField(default=True)),
                ("prints_mention", models.BooleanField(default=True)),
                ("is_rectifying", models.BooleanField(default=False)),
                ("allow_negative", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "fis_doc_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FiscalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("invoice_no", models.CharField(max_length=60, unique=True)),
                ("doc_date", models.DateField()),
                ("system_entry_date", models.DateTimeField()),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "customer_tax_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "net_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "gross_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("previous_hash", models.TextField(blank=True, null=True)),
                ("doc_hash", models.TextField()),
                ("key_version", models.PositiveIntegerField(default=1)),
                (
                    "print_mention",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("qr_data", models.TextField(blank=True, null=True)),
                ("source_billing", models.CharField(default="P", max_length=1)),
                (
                    "reference_doc",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "Normal"), ("A", "Anulado")],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doc_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="fiscal.fiscaldoctype",
                    ),
                ),
            ],
            options={
                "db_table": "fis_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FiscalDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "exemption_reason",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="fiscal.fiscaldocument",
                    ),
                ),
            ],
            options={
                "db_table": "fis_document_line",
            },
        ),
        migrations.CreateModel(
            name="FiscalSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                (
                    "establishment",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("year", models.PositiveIntegerField(default=2026)),
                ("prefix", models.CharField(blank=True, max_length=10, null=True)),
                ("current_number", models.PositiveIntegerField(default=0)),
                ("key_version", models.PositiveIntegerField(default=1)),
                ("certified", models.BooleanField(default=True)),
                ("environment", models.CharField(default="TEST", max_length=4)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doc_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series",
                        to="fiscal.fiscaldoctype",
                    ),
                ),
            ],
            options={
                "db_table": "fis_series",
                "ordering": ["doc_type", "code"],
                "unique_together": {("code", "doc_type", "year")},
            },
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="fiscal.fiscalseries",
            ),
        ),
        migrations.CreateModel(
            name="SubmissionQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Em fila"),
                            ("SENT", "Enviado"),
                            ("ACK", "Aceite"),
                            ("REJECTED", "Rejeitado"),
                            ("RETRY", "A reenviar"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("response", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="fiscal.fiscaldocument",
                    ),
                ),
            ],
            options={
                "db_table": "fis_submission",
                "ordering": ["-created_at"],
            },
        ),
    ]
