# Generated by Django 6.0.4 on 2026-07-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AGTConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="AGT", max_length=60)),
                (
                    "environment",
                    models.CharField(
                        choices=[("SANDBOX", "Sandbox / Testes"), ("PROD", "Produção")],
                        default="SANDBOX",
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("url_auth", models.CharField(blank=True, max_length=300, null=True)),
                ("url_submit", models.CharField(blank=True, max_length=300, null=True)),
                ("url_query", models.CharField(blank=True, max_length=300, null=True)),
                ("url_cancel", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "url_download",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("url_saft", models.CharField(blank=True, max_length=300, null=True)),
                ("url_health", models.CharField(blank=True, max_length=300, null=True)),
                ("client_id", models.CharField(blank=True, max_length=200, null=True)),
                ("client_secret_enc", models.TextField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=120, null=True)),
                ("password_enc", models.TextField(blank=True, null=True)),
                ("api_key_enc", models.TextField(blank=True, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("max_retries", models.PositiveIntegerField(default=5)),
                (
                    "last_health_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("last_health_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "fis_agt_connection",
            },
        ),
        migrations.CreateModel(
            name="DigitalCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=80)),
                ("cert_type", models.CharField(default="X.509", max_length=40)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("issued_by", models.CharField(blank=True, max_length=200, null=True)),
                ("issued_to", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "fingerprint",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("algorithm", models.CharField(default="RSA-SHA1", max_length=40)),
                ("key_bits", models.PositiveIntegerField(default=1024)),
                ("issued_at", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("EXPIRED", "Expirado"),
                            ("REVOKED", "Revogado"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("public_key_pem", models.TextField(blank=True, null=True)),
                ("private_key_enc", models.TextField(blank=True, null=True)),
                ("private_key_password_enc", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fis_certificate",
                "ordering": ["-is_default", "alias"],
            },
        ),
    ]
