# Generated by Django 6.0.4 on 2026-07-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0002_agtconnection_digitalcertificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxExemptionReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12, unique=True)),
                ("description", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "fis_exemption_reason",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("tax_type", models.CharField(default="IVA", max_length=10)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_exempt", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "fis_tax_rate",
                "ordering": ["-percentage", "code"],
            },
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="auto_emit_pos",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="default_exemption_code",
            field=models.CharField(default="M99", max_length=12),
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="invoice_doc_type",
            field=models.CharField(default="FT", max_length=6),
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="pos_doc_type",
            field=models.CharField(default="FR", max_length=6),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="source_module",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="source_ref",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
