# Generated by Django 6.0.4 on 2026-07-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0003_taxexemptionreason_taxrate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalconfig",
            name="address_line",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="city",
            field=models.CharField(default="Luanda", max_length=80),
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="crc_number",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="email",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="fax",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="logo_url",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="phone",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="province",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="share_capital",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="fiscalconfig",
            name="trade_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="amount_in_words",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="customer_address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="discount_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="operator_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="payment_method",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="place_ref",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="print_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="room_ref",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
