# Generated by Django 6.0.4 on 2026-07-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0004_fiscalconfig_address_line_fiscalconfig_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalconfig",
            name="prices_include_tax",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="tax_inclusive",
            field=models.BooleanField(default=True),
        ),
    ]
