# Generated by Django 6.0.4 on 2026-07-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0005_fiscalconfig_prices_include_tax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscaldocument",
            name="agt_status",
            field=models.CharField(default="PENDING", max_length=10),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="settled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CommercialDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BUDGET", "Orçamento"),
                            ("PROFORMA", "Proforma"),
                            ("ORDER", "Encomenda de Cliente"),
                        ],
                        default="BUDGET",
                        max_length=10,
                    ),
                ),
                ("number", models.CharField(max_length=40, unique=True)),
                ("year", models.PositiveIntegerField(default=2026)),
                ("seq", models.PositiveIntegerField(default=0)),
                ("doc_date", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "customer_tax_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "customer_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "operator_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("notes", models.CharField(blank=True, max_length=400, null=True)),
                ("tax_inclusive", models.BooleanField(default=True)),
                (
                    "net_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "gross_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("APPROVAL", "Em Aprovação"),
                            ("APPROVED", "Aprovado"),
                            ("SENT", "Enviado"),
                            ("ACCEPTED", "Aceite"),
                            ("REJECTED", "Rejeitado"),
                            ("EXPIRED", "Expirado"),
                            ("CONVERTED", "Convertido"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=60, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "converted_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_commercial",
                        to="fiscal.fiscaldocument",
                    ),
                ),
            ],
            options={
                "db_table": "fis_commercial_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommercialDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                ("tax_code", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "exemption_reason",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="fiscal.commercialdocument",
                    ),
                ),
            ],
            options={
                "db_table": "fis_commercial_line",
            },
        ),
    ]
