# Generated by Django 6.0.4 on 2026-07-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fiscal",
            "0006_fiscaldocument_agt_status_fiscaldocument_is_archived_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SaftExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("filename", models.CharField(max_length=160)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("problems", models.TextField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fis_saft_export",
                "ordering": ["-created_at"],
            },
        ),
    ]
