# Generated by Django 6.0.4 on 2026-07-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0007_saftexport"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionqueue",
            name="acked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submissionqueue",
            name="agt_reference",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="submissionqueue",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submissionqueue",
            name="http_status",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submissionqueue",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="submissionqueue",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submissionqueue",
            name="payload",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submissionqueue",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Em fila"),
                    ("SENDING", "A enviar"),
                    ("SENT", "Enviado"),
                    ("ACK", "Aceite pela AGT"),
                    ("REJECTED", "Rejeitado"),
                    ("RETRY", "A reenviar"),
                    ("FAILED", "Falhou (esgotou tentativas)"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
    ]
