# Generated by Django 6.0.4 on 2026-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0008_submissionqueue_acked_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=120)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("iban", models.CharField(blank=True, max_length=60, null=True)),
                ("swift", models.CharField(blank=True, max_length=20, null=True)),
                ("currency", models.CharField(default="AOA", max_length=10)),
                (
                    "account_holder",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("show_on_invoice", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "fis_bank_account",
                "ordering": ["sort_order", "bank_name"],
            },
        ),
    ]
