# Generated by Django 6.0.4 on 2026-07-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0009_companybankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="companybankaccount",
            name="bic",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="companybankaccount",
            name="branch",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="companybankaccount",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="companybankaccount",
            name="nib",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="companybankaccount",
            name="sepa",
            field=models.BooleanField(default=False),
        ),
    ]
