# Generated by Django 6.0.4 on 2026-07-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0010_companybankaccount_bic_companybankaccount_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxrate",
            name="accounting_account",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="tax_class",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="TaxRateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="fiscal.taxrate",
                    ),
                ),
            ],
            options={
                "db_table": "fis_tax_rate_version",
                "ordering": ["valid_from"],
            },
        ),
    ]
