# Generated by Django 6.0.4 on 2026-07-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0011_taxrate_accounting_account_taxrate_tax_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxexemptionreason",
            name="text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="taxexemptionreason",
            name="description",
            field=models.CharField(max_length=400),
        ),
    ]
