# Generated by Django 6.0.4 on 2026-07-12 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0012_taxexemptionreason_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalseries",
            name="at_processing_mean",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="fiscalseries",
            name="copy_texts",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="fiscalseries",
            name="document_class",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="fiscalseries",
            name="einvoice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fiscalseries",
            name="einvoice_reference",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="fiscalseries",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fiscalseries",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="fiscalseries",
            name="recovery_series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recovers",
                to="fiscal.fiscalseries",
            ),
        ),
        migrations.AddField(
            model_name="fiscalseries",
            name="series_type",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="fiscalseries",
            name="series_type_2",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="fiscalseries",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fiscalseries",
            name="validation_code",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.CreateModel(
            name="DocPrintModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Talão"),
                            ("INVOICE", "Fatura"),
                            ("REPORT", "Relatório"),
                        ],
                        default="RECEIPT",
                        max_length=10,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("model_name", models.CharField(default="ML.INVOICE", max_length=60)),
                ("copies", models.PositiveSmallIntegerField(default=1)),
                ("max_copies", models.PositiveSmallIntegerField(default=3)),
                ("sort_order", models.PositiveSmallIntegerField(default=1)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_models",
                        to="fiscal.fiscalseries",
                    ),
                ),
            ],
            options={
                "db_table": "fis_print_model",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
