# Generated by Django 6.0.4 on 2026-07-13 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0013_fiscalseries_at_processing_mean_and_more"),
        ("mdm", "0012_customer_member_card_customer_member_card_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscaldocument",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiscal_documents",
                to="mdm.customer",
            ),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
