# Generated by Django 6.0.4 on 2026-07-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eae", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allowed_modules",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="allowed_screens",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_access",
            field=models.BooleanField(default=True),
        ),
    ]
