# Generated by Django 6.0.4 on 2026-07-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("supplier_name", models.CharField(max_length=200)),
                ("supplier_id_ref", models.IntegerField(blank=True, null=True)),
                (
                    "supplier_ref",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("grn_ref", models.CharField(blank=True, max_length=60, null=True)),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Em aberto"),
                            ("PARTIAL", "Parcial"),
                            ("PAID", "Paga"),
                            ("CANCELLED", "Anulada"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fin_supplier_invoice",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="supplier_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="finance.supplierinvoice",
            ),
        ),
    ]
