# Generated by Django 6.0.4 on 2026-07-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_supplierinvoice_paymentvoucher_supplier_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="finance.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Rascunho"),
                    ("ISSUED", "Emitida"),
                    ("PARTIAL", "Parcial"),
                    ("PAID", "Paga"),
                    ("CANCELLED", "Anulada"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
