# Generated by Django 6.0.4 on 2026-07-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_receipt_invoice_alter_invoice_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement_date", models.DateField()),
                (
                    "statement_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "system_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Em curso"), ("CLOSED", "Fechada")],
                        default="DRAFT",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="finance.financeaccount",
                    ),
                ),
            ],
            options={
                "db_table": "fin_reconciliation",
                "ordering": ["-statement_date"],
            },
        ),
    ]
