# Generated by Django 6.0.4 on 2026-07-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_bankreconciliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierinvoice",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
