# Generated by Django 6.0.4 on 2026-07-09 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("mdm", "0004_bank_country_currency_customer_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("currency", models.CharField(default="AOA", max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inv_price_list",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="allow_fraction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="barcode",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="mdm.brand",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="is_purchased",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="is_sold",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="max_stock",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="min_stock",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="item",
            name="purchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list_entries",
                        to="inventory.item",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.pricelist",
                    ),
                ),
            ],
            options={
                "db_table": "inv_price_list_item",
                "unique_together": {("price_list", "item")},
            },
        ),
    ]
