# Generated by Django 6.0.4 on 2026-07-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_pricelist_item_allow_fraction_item_barcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "qty_factor",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Quantidade em unidades-base consumidas (½ dose = 0.5).",
                        max_digits=10,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "inv_item_variant",
                "ordering": ["item", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ItemUom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        help_text="Unidades-base por 1 desta unidade (Caixa de 24 → 24).",
                        max_digits=14,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Compra"),
                            ("SALE", "Venda"),
                            ("BOTH", "Ambas"),
                        ],
                        default="BOTH",
                        max_length=10,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uoms",
                        to="inventory.item",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="item_uoms",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "inv_item_uom",
                "unique_together": {("item", "uom")},
            },
        ),
    ]
