# Generated by Django 6.0.4 on 2026-07-09 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_itemvariant_itemuom"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "Entrada"),
                            ("OUT", "Saída"),
                            ("ADJUST", "Ajuste"),
                            ("TRANSFER_IN", "Transferência (Entrada)"),
                            ("TRANSFER_OUT", "Transferência (Saída)"),
                            ("GRN", "Receção de Compra"),
                            ("CONSUMPTION", "Consumo/Produção"),
                        ],
                        max_length=15,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("reference", models.CharField(blank=True, max_length=80, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="inventory.item",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inv_stock_movement",
                "ordering": ["-created_at"],
            },
        ),
    ]
