# Generated by Django 6.0.4 on 2026-07-11 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_stockmovement"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Em contagem"),
                            ("CONFIRMED", "Confirmado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counts",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inv_count",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCountLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "counted_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.inventorycount",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="count_lines",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "inv_count_line",
            },
        ),
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("BIN", "Bin/Prateleira"),
                            ("AISLE", "Corredor"),
                            ("ZONE", "Zona"),
                            ("COLD", "Câmara Fria"),
                            ("FREEZER", "Congelação"),
                            ("DOCK", "Cais"),
                            ("OTHER", "Outro"),
                        ],
                        default="BIN",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inv_location",
                "ordering": ["warehouse", "code"],
                "unique_together": {("warehouse", "code")},
            },
        ),
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_number", models.CharField(max_length=60)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("received_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="inventory.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lots",
                        to="inventory.stocklocation",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inv_lot",
                "ordering": ["expiry_date", "received_at"],
            },
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("CONFIRMED", "Confirmada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inv_transfer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockTransferLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stocktransfer",
                    ),
                ),
            ],
            options={
                "db_table": "inv_transfer_line",
            },
        ),
    ]
