# Generated by Django 6.0.4 on 2026-07-12 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0002_loyaltyprogram_loyaltytier"),
        ("inventory", "0005_inventorycount_inventorycountline_stocklocation_and_more"),
        ("pos", "0019_posticketline_is_void_posticketline_kds_ack_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Grupo de Artigos",
                "verbose_name_plural": "Grupos de Artigos",
                "db_table": "inv_item_group",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="accounting_account",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="allow_tax_change_on_purchase",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="always_ask_quantity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="analytic_account_purchase",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="analytic_account_sale",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="base_measure_value",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="item",
            name="comment_type_1",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="comment_type_2",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="comment_type_3",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="composition_image_url",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="created_by",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="discounts",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="commercial.promotion"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="exemption_code_1",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="exemption_code_2",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="free_text",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="has_recipe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="is_menu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="is_value_discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="key_image_url",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="manual_price",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="name_lang_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="name_lang_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="name_lang_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="no_discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="no_stock_movement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="plu_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="pms_reference",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="prep_time_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="purchase_exemption_code",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="purchase_tax_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="purchase_uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_purchase",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="recipe_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="report_definition",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="sale_uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_sale",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="scale_interface",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="stock_uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_stock",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="tax_2_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="updated_by",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.CreateModel(
            name="ItemFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="families",
                        to="inventory.itemgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Família",
                "verbose_name_plural": "Famílias",
                "db_table": "inv_item_family",
                "ordering": ["sort_order", "name"],
                "unique_together": {("group", "code")},
            },
        ),
        migrations.CreateModel(
            name="ItemSubFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfamilies",
                        to="inventory.itemfamily",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-Família",
                "verbose_name_plural": "Sub-Famílias",
                "db_table": "inv_item_subfamily",
                "ordering": ["sort_order", "name"],
                "unique_together": {("family", "code")},
            },
        ),
        migrations.AddField(
            model_name="item",
            name="subfamily",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="inventory.itemsubfamily",
            ),
        ),
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "station",
                    models.CharField(
                        choices=[
                            ("KITCHEN", "Cozinha"),
                            ("BAR", "Bar"),
                            ("PASTRY", "Pastelaria"),
                            ("CASHIER", "Caixa"),
                        ],
                        default="KITCHEN",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printers",
                        to="pos.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "inv_printer",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="printers",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="inventory.printer"
            ),
        ),
        migrations.CreateModel(
            name="ItemBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(db_index=True, max_length=64)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                ("is_main", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="inventory.item",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "inv_item_barcode",
                "unique_together": {("item", "barcode")},
            },
        ),
        migrations.CreateModel(
            name="ItemPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "inv_item_price",
                "ordering": ["level"],
                "unique_together": {("item", "level")},
            },
        ),
    ]
