# Generated by Django 6.0.4 on 2026-07-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_itemgroup_item_accounting_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemfamily",
            name="accounting_account",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="itemgroup",
            name="accounting_account",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="itemsubfamily",
            name="accounting_account",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
