# Generated by Django 6.0.4 on 2026-07-12 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_itemfamily_accounting_account_and_more"),
        ("pos", "0019_posticketline_is_void_posticketline_kds_ack_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemsubfamily",
            name="print_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SubFamilyMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pms_charge_code",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "pms_charge_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfamily_mappings",
                        to="pos.outlet",
                    ),
                ),
                (
                    "subfamily",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="inventory.itemsubfamily",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subfamily_mappings",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inv_subfamily_mapping",
                "unique_together": {("subfamily", "outlet")},
            },
        ),
    ]
