# Generated by Django 6.0.4 on 2026-07-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_itemsubfamily_print_order_subfamilymapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemfamily",
            name="code",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="itemsubfamily",
            name="code",
            field=models.CharField(max_length=40),
        ),
    ]
