# Generated by Django 6.0.4 on 2026-07-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_reportdefinition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unitofmeasure",
            options={"ordering": ["code"]},
        ),
        migrations.AddField(
            model_name="unitofmeasure",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="unitofmeasure",
            name="rounding",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="UomConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factor",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "to_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="converted_from",
                        to="inventory.unitofmeasure",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "inv_uom_conversion",
                "unique_together": {("uom", "to_uom")},
            },
        ),
    ]
