# Generated by Django 6.0.4 on 2026-07-12 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0011_alter_unitofmeasure_options_unitofmeasure_is_active_and_more",
        ),
        ("pos", "0031_poshardware"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="printers",
                to="pos.poshardware",
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="warn_on_failure",
            field=models.BooleanField(default=True),
        ),
    ]
