# Generated by Django 6.0.4 on 2026-07-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_warehouse_accounting_account_warehouse_address1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="kds_station",
            field=models.CharField(
                choices=[
                    ("KITCHEN", "Cozinha"),
                    ("BAR", "Bar"),
                    ("PASTRY", "Pastelaria"),
                    ("NONE", "Sem produção"),
                ],
                default="KITCHEN",
                max_length=10,
            ),
        ),
    ]
