# Generated by Django 6.0.4 on 2026-07-28 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_item_kds_station"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AddField(
            model_name="recipe",
            name="doses",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="recipe",
            name="pax",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="waste_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name="ItemChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=80)),
                ("old_value", models.CharField(blank=True, max_length=500, null=True)),
                ("new_value", models.CharField(blank=True, max_length=500, null=True)),
                ("changed_by", models.CharField(blank=True, max_length=80, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
