# Generated by Django 6.0.4 on 2026-07-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_alter_recipeingredient_options_recipe_doses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemsubfamily",
            name="default_tax_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
