# Generated by Django 6.0.4 on 2026-07-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("pos", "0010_postable_pos_x_postable_pos_y_postable_shape"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combos",
                        to="pos.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "com_combo",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ComboItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commercial.combo",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combo_items",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "com_combo_item",
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("ALL", "Todos os artigos"),
                            ("CATEGORY", "Categoria"),
                            ("ITEM", "Artigo"),
                        ],
                        default="ALL",
                        max_length=10,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENT", "Percentagem"), ("FIXED", "Valor fixo")],
                        default="PERCENT",
                        max_length=8,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("happy_start", models.TimeField(blank=True, null=True)),
                ("happy_end", models.TimeField(blank=True, null=True)),
                (
                    "weekdays",
                    models.CharField(
                        blank=True,
                        help_text="Dias (0=Seg … 6=Dom), separados por vírgula. Vazio = todos.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="inventory.itemcategory",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="inventory.item",
                    ),
                ),
                (
                    "outlet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vazio = todos os outlets",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="pos.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "com_promotion",
                "ordering": ["-priority", "name"],
            },
        ),
    ]
