# Generated by Django 6.0.4 on 2026-07-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "points_per_currency",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Pontos ganhos por cada unidade monetária gasta.",
                        max_digits=8,
                    ),
                ),
                (
                    "redeem_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Valor (Kz) de cada ponto no resgate.",
                        max_digits=8,
                    ),
                ),
                ("min_redeem_points", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "com_loyalty_program",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("min_points", models.PositiveIntegerField(default=0)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("benefits", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="commercial.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "db_table": "com_loyalty_tier",
                "ordering": ["min_points"],
            },
        ),
    ]
