# Generated by Django 6.0.4 on 2026-07-08 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Peripheral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peripheral_type",
                    models.CharField(
                        choices=[
                            ("Printer", "Impressora"),
                            ("Drawer", "Gaveta de Dinheiro"),
                            ("Scanner", "Leitor de Códigos de Barras"),
                            ("Display", "Display de Cliente"),
                            ("Scale", "Balança"),
                            ("PaymentTerminal", "Terminal de Pagamento (TPA)"),
                            ("RFIDReader", "Leitor RFID"),
                            ("Biometric", "Leitor Biométrico"),
                        ],
                        max_length=50,
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("mac_address", models.CharField(blank=True, max_length=50, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("Network", "Rede (TCP/IP)"),
                            ("USB", "USB"),
                            ("Serial", "Série (RS232)"),
                            ("Bluetooth", "Bluetooth"),
                        ],
                        default="Network",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Disponível"),
                            ("InUse", "Em Uso"),
                            ("Offline", "Offline"),
                            ("Broken", "Avariado"),
                            ("Repair", "Em Reparação"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peripherals",
                        to="identity.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkstationPeripheral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logical_purpose",
                    models.CharField(
                        choices=[
                            ("Receipt", "Faturas/Talões"),
                            ("Kitchen_Hot", "Cozinha Quente"),
                            ("Kitchen_Cold", "Cozinha Fria"),
                            ("Bar_Drinks", "Bar Bebidas"),
                            ("Drawer_1", "Gaveta Principal"),
                            ("Customer_Display", "Display Cliente"),
                            ("Payment_Primary", "TPA Principal"),
                            ("Scanner_Primary", "Scanner Principal"),
                            ("Auth_Reader", "Leitor de Autenticação (RFID/Bio)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("connection_params", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "peripheral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="ewm.peripheral",
                    ),
                ),
                (
                    "workstation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attached_peripherals",
                        to="identity.workstation",
                    ),
                ),
            ],
            options={
                "unique_together": {("workstation", "peripheral")},
            },
        ),
    ]
