# Generated by Django 6.0.4 on 2026-07-08 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("POS", "Ponto de Venda"),
                            ("STK", "Stock & Inventário"),
                            ("PRC", "Compras (Procurement)"),
                            ("FIN", "Financeiro"),
                            ("HR", "Recursos Humanos"),
                            ("CRM", "CRM & Fidelização"),
                            ("BI", "Business Intelligence"),
                            ("CORE", "Core ERP"),
                        ],
                        max_length=10,
                    ),
                ),
                ("default_state", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeatureOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.company",
                    ),
                ),
                (
                    "feature_flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="fme.featureflag",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.enterprisegroup",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Override",
                "verbose_name_plural": "Feature Overrides",
            },
        ),
    ]
