# Generated by Django 6.0.4 on 2026-07-08 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLogCLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("details", models.JSONField(blank=True, null=True)),
                ("user_identity", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Pessoa Singular"),
                            ("COMPANY", "Empresa"),
                            ("GROUP", "Grupo Empresarial"),
                        ],
                        default="COMPANY",
                        max_length=20,
                    ),
                ),
                ("commercial_name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nif",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "commercial_registry",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(default="Angola", max_length=100)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "general_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("language", models.CharField(default="pt-PT", max_length=20)),
                ("currency", models.CharField(default="AOA", max_length=10)),
                ("timezone", models.CharField(default="Africa/Luanda", max_length=50)),
                ("logo_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LEAD", "Lead"),
                            ("PROSPECT", "Prospect"),
                            ("DEMO", "Demonstração"),
                            ("TRIAL", "Trial"),
                            ("ACTIVE", "Ativo"),
                            ("SUSPENDED", "Suspenso"),
                            ("EXPIRED", "Expirado"),
                            ("CANCELED", "Cancelado"),
                        ],
                        default="LEAD",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommercialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.CharField(max_length=100)),
                ("reseller", models.CharField(blank=True, max_length=100, null=True)),
                ("partner", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "responsible_consultant",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contract_date", models.DateField(blank=True, null=True)),
                ("activation_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("periodicity", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commercial_data",
                        to="clm.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DIRECTOR", "Diretor Geral"),
                            ("FINANCE", "Financeiro"),
                            ("PURCHASING", "Compras"),
                            ("IT", "TI"),
                            ("SUPPORT", "Suporte"),
                            ("ACCOUNTING", "Contabilidade"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=50, null=True)),
                ("language", models.CharField(default="pt-PT", max_length=20)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="clm.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("install_type", models.CharField(default="PRODUCTION", max_length=50)),
                ("server_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
                ("last_ping", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="clm.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_type", models.CharField(max_length=50)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to="clm.installation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=100, unique=True)),
                ("plan", models.CharField(max_length=100)),
                ("modules", models.JSONField(default=list)),
                ("feature_flags", models.JSONField(default=dict)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_offline", models.BooleanField(default=True)),
                ("max_hotels", models.IntegerField(default=1)),
                ("max_pos", models.IntegerField(default=1)),
                ("max_users", models.IntegerField(default=5)),
                ("max_rooms", models.IntegerField(default=0)),
                ("max_events", models.IntegerField(default=0)),
                ("max_apis", models.IntegerField(default=0)),
                ("signature", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="clm.client",
                    ),
                ),
            ],
        ),
    ]
