# Generated by Django 6.0.7 on 2026-07-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminalLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("POS", "Point of Sale"),
                            ("KIOSK", "Kiosk"),
                            ("TABLET", "Tablet Room Service"),
                            ("KDS", "Kitchen Display System"),
                            ("PAYMENT", "Terminal de Pagamento"),
                        ],
                        default="POS",
                        max_length=50,
                    ),
                ),
                ("terminal_id", models.CharField(max_length=50, unique=True)),
                (
                    "activation_key",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "hardware_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Criado"),
                            ("LICENSED", "Licenciado"),
                            ("ACTIVATED", "Ativado"),
                            ("SUSPENDED", "Suspenso"),
                            ("TRANSFERRED", "Transferido"),
                            ("DEACTIVATED", "Desativado"),
                        ],
                        default="CREATED",
                        max_length=50,
                    ),
                ),
                (
                    "assigned_hotel_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "assigned_department_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("last_ping", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminal_licenses",
                        to="clm.client",
                    ),
                ),
            ],
        ),
    ]
