# Generated by Django 6.0.4 on 2026-07-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clm", "0002_terminallicense"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="agt_certificate_number",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="agt_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="agt_private_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="agt_public_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
