# Generated by Django 6.0.4 on 2026-07-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clm", "0003_license_agt_certificate_number_license_agt_issued_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="agt_connection",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
