# Generated by Django 6.0.4 on 2026-07-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clm", "0004_license_agt_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="install_password_enc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="install_password_set_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="owner_password_enc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="owner_password_set_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="owner_username",
            field=models.CharField(
                blank=True, default="dono", max_length=60, null=True
            ),
        ),
    ]
