# Generated by Django 6.0.4 on 2026-07-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clm", "0005_license_install_password_enc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Ex.: 1.1.0", max_length=20, unique=True
                    ),
                ),
                (
                    "download_url",
                    models.URLField(
                        help_text="Onde o cliente descarrega o .exe desta versão."
                    ),
                ),
                (
                    "release_notes",
                    models.TextField(
                        blank=True,
                        help_text="O que mudou — aparece no aviso do cliente.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "db_table": "clm_system_release",
                "ordering": ["-created_at"],
            },
        ),
    ]
