# Generated by Django 6.0.7 on 2026-08-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clm", "0006_systemrelease"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemrelease",
            name="download_url",
            field=models.URLField(
                help_text='Onde o cliente descarrega esta versão — .exe (instalador completo, manual) ou .zip (pacote leve, ativa o botão "Atualizar agora" de um clique).'
            ),
        ),
    ]
