# Generated by Django 6.0.4 on 2026-08-11 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clm", "0007_alter_systemrelease_download_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_code", models.CharField(blank=True, max_length=50, null=True)),
                ("level", models.CharField(default="ERROR", max_length=20)),
                (
                    "logger_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("message", models.TextField()),
                ("traceback", models.TextField(blank=True, null=True)),
                ("path", models.CharField(blank=True, max_length=300, null=True)),
                ("app_version", models.CharField(blank=True, max_length=50, null=True)),
                ("hostname", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_note", models.TextField(blank=True, null=True)),
                (
                    "installation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_reports",
                        to="clm.installation",
                    ),
                ),
            ],
            options={
                "db_table": "clm_error_report",
                "ordering": ["-created_at"],
            },
        ),
    ]
