# Generated by Django 6.0.4 on 2026-08-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clm", "0008_errorreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="owner_reset_code",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="owner_reset_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
