# Generated by Django 6.0.7 on 2026-07-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esm", "0001_initial"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="purchase_orders",
                to="esm.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceipt",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="esm.supplier"
            ),
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
