# Generated by Django 6.0.4 on 2026-07-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esm", "0001_initial"),
        ("inventory", "0005_inventorycount_inventorycountline_stocklocation_and_more"),
        (
            "procurement",
            "0003_purchaserequisition_requisitionline_rfq_rfqline_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("reason", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("CONFIRMED", "Confirmada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="esm.supplier",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_returns",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "proc_return",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "ret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="procurement.purchasereturn",
                    ),
                ),
            ],
            options={
                "db_table": "proc_return_line",
            },
        ),
    ]
