# Generated by Django 6.0.7 on 2026-07-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "prod_allergen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ItemProductionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_semi_finished",
                    models.BooleanField(
                        default=False,
                        help_text="Semiacabado (usado como ingrediente noutras receitas) vs. produto acabado.",
                    ),
                ),
                (
                    "shelf_life_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("storage_instructions", models.TextField(blank=True, null=True)),
                (
                    "serving_size_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "energy_kcal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "saturated_fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "sugars_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "protein_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "salt_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "fiber_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "allergens",
                    models.ManyToManyField(
                        blank=True, related_name="items", to="production.allergen"
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_profile",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "prod_item_profile",
            },
        ),
        migrations.CreateModel(
            name="ProductionArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("KITCHEN_HOT", "Cozinha Quente"),
                            ("KITCHEN_COLD", "Cozinha Fria"),
                            ("PASTRY", "Pastelaria"),
                            ("BAKERY", "Padaria"),
                            ("BAR", "Bar"),
                            ("BUTCHERY", "Talho"),
                            ("GARDE_MANGER", "Garde Manger"),
                            ("OTHER", "Outra"),
                        ],
                        default="KITCHEN_HOT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_areas",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "prod_area",
                "unique_together": {("hotel", "name")},
            },
        ),
        migrations.CreateModel(
            name="KitchenEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("OVEN", "Forno"),
                            ("COMBI", "Forno Combinado"),
                            ("FRYER", "Fritadeira"),
                            ("GRILL", "Grelhador"),
                            ("STOVE", "Fogão"),
                            ("MIXER", "Misturadora"),
                            ("BLAST_CHILLER", "Abatedor de Temperatura"),
                            ("FRIDGE", "Câmara/Frigorífico"),
                            ("OTHER", "Outro"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("capacity", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to="production.productionarea",
                    ),
                ),
            ],
            options={
                "db_table": "prod_equipment",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("IN_REVIEW", "Em Revisão"),
                            ("APPROVED", "Aprovada"),
                            ("PRODUCTION", "Em Produção"),
                            ("DISCONTINUED", "Descontinuada"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "yield_quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=12),
                ),
                ("prep_time_mins", models.PositiveIntegerField(blank=True, null=True)),
                ("cook_time_mins", models.PositiveIntegerField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
                (
                    "theoretical_cost",
                    models.DecimalField(
                        decimal_places=4, default=0, editable=False, max_digits=14
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipes",
                        to="production.productionarea",
                    ),
                ),
                (
                    "equipments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recipes",
                        to="production.kitchenequipment",
                    ),
                ),
                (
                    "final_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_recipes",
                        to="inventory.item",
                    ),
                ),
                (
                    "yield_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="recipe_yields",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "prod_recipe",
            },
        ),
        migrations.CreateModel(
            name="RecipeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "wastage_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_optional", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "component_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="used_in_recipe_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="production.recipe",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "prod_recipe_line",
            },
        ),
    ]
