# Generated by Django 6.0.4 on 2026-07-11 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("inventory", "0004_stockmovement"),
        ("production", "0002_seed_allergens"),
    ]

    operations = [
        migrations.CreateModel(
            name="FnbMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("ALACARTE", "À la carte"),
                            ("BUFFET", "Buffet"),
                            ("BANQUET", "Banquete"),
                            ("DRINKS", "Carta de Bebidas"),
                            ("ROOMSERVICE", "Room Service"),
                            ("KIDS", "Menu Infantil"),
                            ("SEASONAL", "Sazonal / Especial"),
                        ],
                        default="ALACARTE",
                        max_length=16,
                    ),
                ),
                (
                    "outlet_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RESTAURANT", "Restaurante"),
                            ("BAR", "Bar"),
                            ("POOL_BAR", "Pool Bar / Rooftop"),
                            ("COFFEE", "Coffee Shop"),
                            ("ROOM_SERVICE", "Room Service"),
                            ("BANQUET", "Buffet / Banquete"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fnb_menus",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "fnb_menu",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FnbEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("BANQUET", "Banquete"),
                            ("WEDDING", "Casamento"),
                            ("CONFERENCE", "Conferência"),
                            ("COFFEE_BREAK", "Coffee Break"),
                            ("COCKTAIL", "Cocktail"),
                            ("BUFFET", "Buffet"),
                            ("OTHER", "Outro"),
                        ],
                        default="BANQUET",
                        max_length=16,
                    ),
                ),
                ("event_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("pax", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INQUIRY", "Pedido"),
                            ("CONFIRMED", "Confirmado"),
                            ("IN_PROGRESS", "Em curso"),
                            ("DONE", "Concluído"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="INQUIRY",
                        max_length=12,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fnb_events",
                        to="identity.hotel",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="production.fnbmenu",
                    ),
                ),
            ],
            options={
                "db_table": "fnb_event",
                "ordering": ["event_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="FnbMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=80, null=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                ("is_signature", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="production.fnbmenu",
                    ),
                ),
            ],
            options={
                "db_table": "fnb_menu_item",
                "ordering": ["section", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HaccpCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("TEMP_FRIDGE", "Temperatura — Frio"),
                            ("TEMP_FREEZER", "Temperatura — Congelação"),
                            ("TEMP_COOKING", "Temperatura — Confeção"),
                            ("TEMP_HOLDING", "Temperatura — Manutenção a quente"),
                            ("RECEIVING", "Receção de mercadoria"),
                            ("CLEANING", "Limpeza / Sanitização"),
                            ("HYGIENE", "Higiene pessoal"),
                        ],
                        default="TEMP_FRIDGE",
                        max_length=16,
                    ),
                ),
                (
                    "location_label",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "measured_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("unit", models.CharField(default="°C", max_length=10)),
                (
                    "limit_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "limit_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("compliant", models.BooleanField(default=True)),
                (
                    "corrective_action",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("checked_by", models.CharField(blank=True, max_length=120, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="haccp_checks",
                        to="production.productionarea",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="haccp_checks",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "fnb_haccp_check",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outlet_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RESTAURANT", "Restaurante"),
                            ("BAR", "Bar"),
                            ("POOL_BAR", "Pool Bar / Rooftop"),
                            ("COFFEE", "Coffee Shop"),
                            ("ROOM_SERVICE", "Room Service"),
                            ("BANQUET", "Buffet / Banquete"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("subject", models.CharField(max_length=160)),
                ("score", models.PositiveSmallIntegerField(default=5)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Conforme"),
                            ("WARN", "A melhorar"),
                            ("FAIL", "Não conforme"),
                        ],
                        default="PASS",
                        max_length=6,
                    ),
                ),
                ("inspector", models.CharField(blank=True, max_length=120, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_checks",
                        to="production.productionarea",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to="identity.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "fnb_quality_check",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="WasteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=160)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPOILAGE", "Deterioração"),
                            ("OVERPRODUCTION", "Sobreprodução"),
                            ("PREPARATION", "Preparação / Aparas"),
                            ("EXPIRED", "Validade expirada"),
                            ("RETURN", "Devolução de cliente"),
                            ("BREAKAGE", "Quebra / Acidente"),
                            ("OTHER", "Outro"),
                        ],
                        default="SPOILAGE",
                        max_length=16,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "recorded_by",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waste_records",
                        to="production.productionarea",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_records",
                        to="identity.hotel",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waste_records",
                        to="inventory.item",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waste_records",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "fnb_waste",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
