# Generated by Django 6.0.4 on 2026-07-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_itemsubfamily_print_order_subfamilymapping"),
        (
            "production",
            "0003_fnbmenu_fnbevent_fnbmenuitem_haccpcheck_qualitycheck_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PosMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_message", models.BooleanField(default=True)),
                ("is_comment", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Mensagem do POS",
                "verbose_name_plural": "Mensagens do POS",
                "db_table": "prod_pos_message",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.AddField(
            model_name="allergen",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="allergen",
            name="photo_url",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.CreateModel(
            name="PosMessageOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_label", models.CharField(max_length=60)),
                ("print_label", models.CharField(max_length=60)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("on_emenu", models.BooleanField(default=False)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="production.posmessage",
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_options",
                        to="inventory.printer",
                    ),
                ),
            ],
            options={
                "db_table": "prod_pos_message_option",
                "ordering": ["sort_order", "key_label"],
            },
        ),
    ]
