# Generated by Django 6.0.4 on 2026-07-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("doc_type", models.CharField(max_length=40)),
                (
                    "page_format",
                    models.CharField(
                        choices=[
                            ("A4", "A4"),
                            ("A5", "A5"),
                            ("THERMAL_80", "Talão 80mm"),
                            ("THERMAL_58", "Talão 58mm"),
                        ],
                        default="A4",
                        max_length=12,
                    ),
                ),
                ("header", models.TextField(blank=True, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("footer", models.TextField(blank=True, null=True)),
                ("show_logo", models.BooleanField(default=True)),
                ("show_qr", models.BooleanField(default=True)),
                ("signature_enabled", models.BooleanField(default=False)),
                (
                    "signature_label",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cfg_document_template",
                "ordering": ["doc_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LOCK", "Fechaduras eletrónicas"),
                            ("BANK_POS", "TPA / Terminal de pagamento"),
                            ("SCALE", "Balança"),
                            ("PRINTER", "Impressora"),
                            ("API", "API externa"),
                        ],
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("vendor", models.CharField(blank=True, max_length=120, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIGURED", "Configurado"),
                            ("PENDING", "Pendente"),
                            ("ERROR", "Erro"),
                            ("DISABLED", "Desativado"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cfg_integration_connector",
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("provider", models.CharField(blank=True, max_length=120, null=True)),
                ("sender", models.CharField(blank=True, max_length=160, null=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cfg_notification_channel",
                "ordering": ["channel", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("task_type", models.CharField(max_length=40)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("HOURLY", "De hora a hora"),
                            ("DAILY", "Diária"),
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensal"),
                        ],
                        default="DAILY",
                        max_length=10,
                    ),
                ),
                ("run_at", models.CharField(blank=True, max_length=10, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cfg_scheduled_task",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=140)),
                ("template", models.TextField(blank=True, null=True)),
                ("recipients", models.CharField(blank=True, max_length=255, null=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules",
                        to="core.notificationchannel",
                    ),
                ),
            ],
            options={
                "db_table": "cfg_notification_rule",
                "ordering": ["event"],
            },
        ),
    ]
