# Generated by Django 6.0.4 on 2026-07-12 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_workflowflow_workflowtask"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criado"),
                            ("UPDATE", "Alterado"),
                            ("DELETE", "Eliminado"),
                            ("VOID", "Anulado"),
                            ("VIEW", "Consultado"),
                            ("EXPORT", "Exportado"),
                            ("LOGIN", "Entrada no sistema"),
                            ("LOGOUT", "Saída"),
                            ("DENIED", "Acesso recusado"),
                            ("PRINT", "Impresso"),
                            ("SUBMIT", "Comunicado à AGT"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("module", models.CharField(db_index=True, max_length=40)),
                (
                    "area",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                ("entity", models.CharField(db_index=True, max_length=60)),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                ("label", models.CharField(max_length=250)),
                (
                    "user",
                    models.CharField(
                        blank=True, db_index=True, max_length=120, null=True
                    ),
                ),
                ("ip_address", models.CharField(blank=True, max_length=60, null=True)),
                ("hotel_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("search_text", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "core_audit_event",
                "ordering": ["-at"],
                "indexes": [
                    models.Index(
                        fields=["module", "-at"], name="core_audit__module_f195dd_idx"
                    ),
                    models.Index(
                        fields=["entity", "entity_id"],
                        name="core_audit__entity_f96c10_idx",
                    ),
                ],
            },
        ),
    ]
