# Generated by Django 6.0.4 on 2026-07-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auditevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Currency",
        ),
    ]
